/* oxlint-disable no-console -- dev tooling log output */

/*
 * The whole reference stack, on this machine (#1909).
 *
 *   pnpm --filter @codaco/studio-server dev:stack
 *   pnpm --filter @codaco/studio-server dev:stack:down
 *
 * `dev` runs the backing services in containers and the Studio processes from
 * source; this runs what a self-hoster runs — Traefik terminating TLS, nginx
 * serving the built client, the API and the worker from the `studio-api`
 * image, the `migrate` one-shot — against `https://localhost`. It is how the
 * routing table, the maintenance page, the first-run setup screen and an
 * upgrade are exercised before any of them reach someone else's host.
 *
 * Three differences from a deployment, all in `../../docker-compose.local.yml`
 * and all about the hostname: a self-signed certificate rather than ACME, a
 * Mailpit sink rather than an SMTP provider, and images built from this
 * checkout rather than pulled. The stack's own file is not modified.
 *
 * It runs beside `pnpm dev`: a different Compose project, a different subnet,
 * and no published port either lane wants (the stack publishes 80 and 443,
 * which the development lane does not use, and its Mailpit takes an ephemeral
 * port rather than the development lane's 1025 and 8025).
 */

import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { DEV } from '../src/env/catalogue.ts';
import {
  composeFile,
  createCompose,
  localComposeFile,
  repositoryRoot,
  studioRoot,
  writeSecretsIfAbsent,
} from './compose.ts';

/**
 * Not `studio` (the compose file's own name) and not `studio-dev`: a developer
 * running both lanes has three projects on one machine, and a `down` must only
 * ever tear apart the one it was aimed at.
 */
const PROJECT = 'studio-stack';

const HOSTNAME = 'localhost';
const API_IMAGE = 'studio-api:local';
const WEB_IMAGE = 'studio-web:local';

/**
 * A third subnet, so this stack, the development lane's (172.31.241.0/24) and
 * the `.env.example` default (172.31.240.0/24) can all exist at once.
 */
const SUBNET = '172.31.242.0/24';

const envLocalPath = fileURLToPath(new URL('.env.local', studioRoot));
const dockerfile = 'apps/studio/Dockerfile';

/**
 * Read back from an existing `.env.local` rather than regenerated, so
 * restarting the stack does not sign out the owner account created against the
 * last one. Everything else in the file is derived, and is rewritten on every
 * run so a change to `DEV` or to this script reaches the containers.
 */
function authSecret(): string {
  if (existsSync(envLocalPath)) {
    const existing = /^BETTER_AUTH_SECRET=(.+)$/m.exec(
      readFileSync(envLocalPath, 'utf8'),
    );
    if (existing?.[1]) return existing[1];
  }
  return randomBytes(32).toString('base64');
}

/**
 * Every variable `../../docker-compose.yml` interpolates, as a file rather
 * than as this process's environment — unlike the development lane, which
 * exports them. A file is what lets a developer drive the same project by hand
 * with the same values:
 *
 *   docker compose -p studio-stack --env-file apps/studio/.env.local \
 *     -f apps/studio/docker-compose.yml -f apps/studio/docker-compose.local.yml ps
 *
 * The credentials are the development lane's, from `DEV`. They are published
 * values pointing at containers on this machine; the generated signing secret
 * is the one thing that is not, because a session cookie minted under a
 * published secret on `https://localhost` is a cookie any other checkout could
 * mint too.
 */
function renderEnvLocal(): string {
  const lines: [name: string, value: string][] = [
    ['STUDIO_HOSTNAME', HOSTNAME],
    ['ACME_EMAIL', 'nobody@localhost'],
    ['STUDIO_API_IMAGE', API_IMAGE],
    ['STUDIO_WEB_IMAGE', WEB_IMAGE],
    ['STACK_SUBNET', SUBNET],
    ['POSTGRES_USER', DEV.pgUser],
    ['POSTGRES_DB', DEV.pgDatabase],
    ['BETTER_AUTH_SECRET', authSecret()],
    ['S3_REGION', DEV.s3Region],
    ['S3_BUCKET', DEV.s3Bucket],
    ['S3_ACCESS_KEY_ID', DEV.s3AccessKeyId],
    ['S3_SECRET_ACCESS_KEY', DEV.s3SecretAccessKey],
    ['GARAGE_RPC_SECRET', DEV.garageRpcSecret],
    ['GARAGE_ADMIN_TOKEN', DEV.garageAdminToken],
    // The Mailpit container `docker-compose.local.yml` adds, by service name:
    // the worker reaches it over the stack's own network.
    ['SMTP_URL', `smtp://mailpit:${DEV.smtpPort}`],
    ['EMAIL_FROM', DEV.emailFrom],
  ];
  return [
    '# Generated by apps/studio/server/scripts/dev-stack.ts. Gitignored, and',
    '# rewritten on every `dev:stack` run — put nothing here by hand except a',
    '# BETTER_AUTH_SECRET you want kept, which is the one value it reads back.',
    '#',
    '# These are development credentials for containers on this machine. The',
    '# file a deployment writes is `.env`, from `.env.example`.',
    '',
    ...lines.map(([name, value]) => `${name}=${value}`),
    '',
  ].join('\n');
}

const compose = createCompose({
  project: PROJECT,
  files: [composeFile, localComposeFile],
  envFile: envLocalPath,
});

/**
 * Both images, from the monorepo root. Built here rather than left to
 * Compose's own `build` so the output is the ordinary `docker build` progress
 * a developer can read, and so a failure stops before anything is started.
 */
function buildImages(): void {
  const targets: [target: string, tag: string][] = [
    ['studio-api', API_IMAGE],
    ['studio-web', WEB_IMAGE],
  ];
  for (const [target, tag] of targets) {
    console.log(`Building ${tag} (--target ${target})...`);
    const result = spawnSync(
      'docker',
      ['build', '-f', dockerfile, '--target', target, '-t', tag, '.'],
      { cwd: fileURLToPath(repositoryRoot), stdio: 'inherit' },
    );
    if (result.status !== 0) {
      throw new Error(`docker build --target ${target} failed.`);
    }
  }
}

/** Where Docker put Mailpit's inbox, which takes whatever port was free. */
function mailpitInbox(): string | undefined {
  const result = compose.run(['port', 'mailpit', '8025'], { capture: true });
  const address = result.stdout.trim();
  return address
    ? `http://${address.replace('0.0.0.0', '127.0.0.1')}`
    : undefined;
}

/**
 * Deliberately without `--wait`. Between `up` and `migrate` there is no schema
 * for `api` and `worker` to verify, so both exit and are restarted by the
 * runtime — the restart window the compose file's header describes. Waiting
 * for health here would wait for a state that cannot be reached until the next
 * step has run.
 */
function up(): void {
  const result = compose.run(['up', '-d']);
  if (result.status !== 0) {
    throw new Error(`docker compose up failed:\n${result.stderr}`);
  }
}

/**
 * The same command with `--wait`, once there is a schema: it changes nothing
 * that is already running and returns when every service is healthy, so the
 * URL printed afterwards is one that answers rather than one that is about to.
 */
function waitForHealthy(): void {
  const result = compose.run(['up', '-d', '--wait']);
  if (result.status !== 0) {
    throw new Error(
      `The stack did not become healthy after migrate:\n${result.stderr}`,
    );
  }
}

/**
 * The schema, the Garage bootstrap it depends on, and — while the instance has
 * no owner — the first-run setup token. Its output is the point, not its exit
 * code, so it is printed whole.
 */
function migrate(): void {
  console.log('\nRunning migrate...\n');
  const result = compose.run(['run', '--rm', 'migrate']);
  if (result.status !== 0) {
    throw new Error('docker compose run --rm migrate failed.');
  }
}

/**
 * `--profile migrate` because the two one-shots are profile-gated: without it
 * `down` leaves `garage-init` behind — `migrate` depends on it, so Compose
 * creates it as an ordinary container rather than a `--rm` one — and the next
 * `up` then fails with a container attached to a network that no longer
 * exists. It is not an orphan (the file still declares it), so
 * `--remove-orphans` does not reach it either.
 */
function down(removeVolumes: boolean): void {
  const result = compose.run(
    ['down', '--remove-orphans', ...(removeVolumes ? ['--volumes'] : [])],
    { profiles: ['migrate'] },
  );
  if (result.status !== 0) {
    throw new Error(`docker compose down failed:\n${result.stderr}`);
  }
}

/**
 * Compose interpolates the file for every command, teardown included, so the
 * environment has to exist before any of them. Rewritten on an `up` so a
 * change to `DEV` or to this script reaches the containers; on a `down` it is
 * only restored if it is missing, which is what lets `dev:stack:down` work in
 * a checkout where it was never written.
 */
function ensureEnvLocal(rewrite: boolean): void {
  if (!rewrite && existsSync(envLocalPath)) return;
  writeFileSync(envLocalPath, renderEnvLocal(), { mode: 0o600 });
}

function main(argv: readonly string[]): void {
  if (argv.includes('--down')) {
    ensureEnvLocal(false);
    down(argv.includes('--volumes') || argv.includes('-v'));
    console.log(
      argv.includes('--volumes') || argv.includes('-v')
        ? `Stopped ${PROJECT} and removed its volumes.`
        : `Stopped ${PROJECT}. Its volumes are kept; add --volumes to wipe them (a wiped database is a fresh first-run setup).`,
    );
    return;
  }

  buildImages();
  writeSecretsIfAbsent();
  ensureEnvLocal(true);
  console.log('Wrote .env.local — the stack environment for this machine');
  up();
  migrate();
  waitForHealthy();

  const inbox = mailpitInbox();
  console.log(
    [
      '',
      `The stack is up at https://${HOSTNAME} [project: ${PROJECT}]`,
      '',
      'Traefik serves its own self-signed certificate here, so a browser warns and curl needs -k:',
      `  curl -k https://${HOSTNAME}/readyz`,
      '',
      'Open it, enter the setup token above, and create the first owner account.',
      ...(inbox ? ['', `Mail sink   ${inbox} (Mailpit's inbox)`] : []),
      '',
      'Stop it with: pnpm --filter @codaco/studio-server dev:stack:down',
    ].join('\n'),
  );
}

main(process.argv.slice(2));
