import { fileURLToPath } from 'node:url';

import { CATALOGUE, GROUPS, type VariableDoc } from '../src/env/catalogue.ts';

// Pure renderers for the three generated environment artifacts. Kept separate
// from the writer so the drift guard (src/env/__tests__/docs.test.ts) can
// re-render in memory and compare against what is committed, the same split
// packages/fresco-ui uses for its generated exports map.

const COMMAND = 'pnpm --filter @codaco/studio-server generate:env-docs';

const README_MARKER_START = '<!-- generated:env start -->';
const README_MARKER_END = '<!-- generated:env end -->';

const serverRoot = new URL('..', import.meta.url);

export const ENV_DEVELOPMENT_PATH = fileURLToPath(
  new URL('.env.development', serverRoot),
);
export const ENV_EXAMPLE_PATH = fileURLToPath(
  new URL('.env.example', serverRoot),
);
export const README_PATH = fileURLToPath(new URL('../README.md', serverRoot));

type Entry = [name: string, doc: VariableDoc];

function entriesByGroup(group: string): Entry[] {
  return Object.entries(CATALOGUE).filter(([, doc]) => doc.group === group);
}

function fileBanner(what: string): string[] {
  return [
    `# ${what}`,
    `# Generated by \`${COMMAND}\` — do not edit by hand.`,
    '# The source is apps/studio/server/src/env/catalogue.ts.',
  ];
}

function wrap(text: string, width: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    if (line && `${line} ${word}`.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** Env-file comments read better without the Markdown backticks. */
function plain(text: string): string {
  return text.replaceAll('`', '').replaceAll('⇒', '=>').replaceAll('’', "'");
}

export function renderEnvDevelopment(): string {
  const lines = [
    ...fileBanner('Local development defaults for the Studio server.'),
    '#',
    '# Committed on purpose: a fresh clone runs `pnpm --filter',
    '# @codaco/studio-server dev` with no setup. These credentials are',
    '# intentional test values pointing at the Docker containers the dev',
    '# script provisions, and are safe to publish.',
    '#',
    '# No deployment path loads this file. To override a value locally, put it',
    '# in a gitignored `.env` beside this file — the dev script loads that',
    '# second, so it wins.',
  ];

  for (const group of GROUPS) {
    const entries = entriesByGroup(group).filter(([, doc]) => doc.devDefault);
    if (entries.length === 0) continue;
    lines.push('', `# ${group}`);
    for (const [name, doc] of entries) {
      for (const line of wrap(plain(doc.summary), 74)) lines.push(`# ${line}`);
      lines.push(`${name}=${doc.devDefault ?? ''}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

export function renderEnvExample(): string {
  const lines = [
    ...fileBanner('Environment template for a Studio deployment.'),
    '#',
    '# Copy to `.env` and fill in. Every variable is optional at boot: an',
    '# unconfigured surface refuses at request time rather than preventing the',
    '# server from starting.',
  ];

  for (const group of GROUPS) {
    // The development marker is meaningless in a deployment, and refused
    // outright alongside NODE_ENV=production.
    const entries = entriesByGroup(group).filter(
      ([name]) => name !== 'STUDIO_DEV_DEFAULTS',
    );
    if (entries.length === 0) continue;
    lines.push(
      '',
      '# -------------------',
      `# ${group}`,
      '# -------------------',
    );
    for (const [name, doc] of entries) {
      for (const line of wrap(plain(doc.summary), 74)) lines.push(`# ${line}`);
      for (const line of wrap(plain(doc.deployment), 74))
        lines.push(`# ${line}`);
      lines.push(`#${name}=${doc.example ?? ''}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function renderTable(rows: string[][]): string[] {
  const widths = rows[0]!.map((_, column) =>
    Math.max(...rows.map((row) => row[column]!.length)),
  );
  const pad = (row: string[]) =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column]!)).join(' | ')} |`;
  const divider = `| ${widths.map((width) => '-'.repeat(width)).join(' | ')} |`;
  return [pad(rows[0]!), divider, ...rows.slice(1).map(pad)];
}

export function renderReadmeSection(): string {
  const lines = [
    README_MARKER_START,
    '',
    `<!-- Generated by \`${COMMAND}\` from src/env/catalogue.ts. Do not edit by hand. -->`,
  ];

  for (const group of GROUPS) {
    const entries = entriesByGroup(group);
    if (entries.length === 0) continue;
    // The section is spliced under the README's `## Environment`, so these are
    // its direct children — skipping a level would break the outline.
    lines.push('', `### ${group}`, '');
    lines.push(
      ...renderTable([
        ['Variable', 'What it is', 'Development default', 'Real deployment'],
        ...entries.map(([name, doc]) => [
          `\`${name}\``,
          doc.summary,
          doc.devDefault ? `\`${doc.devDefault}\`` : '—',
          doc.deployment,
        ]),
      ]),
    );
  }

  lines.push('', README_MARKER_END);
  return lines.join('\n');
}

export function spliceReadme(readme: string, section: string): string {
  const start = readme.indexOf(README_MARKER_START);
  const end = readme.indexOf(README_MARKER_END);
  if (start === -1 || end === -1) {
    throw new Error(
      `README is missing the ${README_MARKER_START} / ${README_MARKER_END} markers`,
    );
  }
  return (
    readme.slice(0, start) +
    section +
    readme.slice(end + README_MARKER_END.length)
  );
}
