import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { renderSchemaDocs, writeSchemaDocs } from './schema-docs.ts';

const artifacts = await renderSchemaDocs();

writeFileSync(
  fileURLToPath(new URL('../src/db/fingerprint.generated.ts', import.meta.url)),
  [
    '// Generated by scripts/sync-fingerprint.ts — do not edit.',
    '// Resync after any schema or sidecar change:',
    '//   pnpm --filter @codaco/studio-server sync-fingerprint',
    'export const SCHEMA_FINGERPRINT =',
    `  '${artifacts.fingerprint}';`,
    '',
  ].join('\n'),
);
writeSchemaDocs(artifacts);

console.log(`Fingerprint: ${artifacts.fingerprint}`);
console.log('Wrote the Studio ERD and README schema section.');
