import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { computeSchemaFingerprint } from './apply.ts';

const fingerprint = await computeSchemaFingerprint();

writeFileSync(
  fileURLToPath(new URL('../src/db/fingerprint.generated.ts', import.meta.url)),
  [
    '// Generated by scripts/sync-fingerprint.ts — do not edit.',
    '// Resync after any schema or sidecar change:',
    '//   pnpm --filter @codaco/studio-server sync-fingerprint',
    'export const SCHEMA_FINGERPRINT =',
    `  '${fingerprint}';`,
    '',
  ].join('\n'),
);

console.log(`Fingerprint: ${fingerprint}`);
