[build]
command = "pnpm exec turbo run build --filter=@codaco/architect^... && pnpm --filter=@codaco/architect build:web"
publish = "apps/architect/dist"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
