packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@faker-js/faker': ^10.1.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/postcss': ^4.1.0
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/react-table': ^8.21.3
  '@types/node': ^22.18.8
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  dotenv: ^17.2.3
  lucide-react: ^0.553.0
  motion: ^12.23.24
  next: ^16.0.3
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: ^7.2.2
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.9
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - bufferutil
  - core-js
  - esbuild
  - sharp
