packages:
  - apps/*
  - packages/*
  - tooling/*
  - workers/*

catalog:
  '@faker-js/faker': ^10.2.0
  es-toolkit: ^1.43.0
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/container-queries': ^0.1.1
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/react-table': ^8.21.3
  '@types/node': ^24.10.1
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.3
  lucide-react: ^0.562.0
  motion: ^12.24.10
  next: ^16.1.1
  postcss: ^8.5.6
  '@posthog/react': ^1.7.1
  posthog-js: ^1.347.2
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^3.4.18
  tailwindcss-animate: ^1.0.7
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.17
  wrangler: ^4.59.1
  zod: ^4.2.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - bufferutil
  - core-js
  - esbuild
  - sharp
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
