packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@radix-ui/react-accordion": ^1.2.1
  "@radix-ui/react-alert-dialog": ^1.1.2
  "@radix-ui/react-checkbox": ^1.1.2
  "@radix-ui/react-dialog": "^1.1.2"
  "@radix-ui/react-collapsible": ^1.1.1
  "@radix-ui/react-dropdown-menu": ^2.1.2
  "@radix-ui/react-icons": ^1.3.1
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-navigation-menu": ^1.2.1
  "@radix-ui/react-progress": ^1.1.0
  "@radix-ui/react-popover": "^1.1.1"
  "@radix-ui/react-scroll-area": ^1.2.1
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slot": ^1.1.0
  "@radix-ui/react-switch": ^1.1.1
  "@radix-ui/react-tabs": ^1.1.1
  "@radix-ui/react-toast": ^1.2.2
  "@radix-ui/react-tooltip": ^1.1.4
  "@tailwindcss/container-queries": ^0.1.1
  "@tailwindcss/typography": ^0.5.15
  "@tanstack/react-table": ^8.20.5
  "@types/react-dom": ^19.0.3
  "@types/node": ^20
  "@types/react": ^19.0.3
  cmdk: ^1.0.4
  lucide-react: ^0.483.0
  next: 15.2.4
  postcss: ^8.4.35
  react: ^19.0.0
  react-dom: ^19.0.0
  sonner: ^1.7.0
  tailwindcss: ^3.4.17
  motion: ^12.5.0
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^3.0.2
  typescript: ^5.8.2
  zod: ^3.24.2
  vite: ^6.3.5
  vitest: ^3.0.9
  dotenv: ^16.4.7

