packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@radix-ui/react-accordion': ^1.2.1
  '@radix-ui/react-alert-dialog': ^1.1.2
  '@radix-ui/react-checkbox': ^1.1.2
  '@radix-ui/react-collapsible': ^1.1.1
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-icons': ^1.3.1
  '@radix-ui/react-label': ^2.1.0
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.0
  '@radix-ui/react-scroll-area': ^1.2.1
  '@radix-ui/react-select': ^2.1.2
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': ^1.1.0
  '@radix-ui/react-switch': ^1.2.5
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toast': ^1.2.2
  '@radix-ui/react-tooltip': ^1.2.7
  '@tailwindcss/container-queries': ^0.1.1
  '@tailwindcss/typography': ^0.5.15
  '@tanstack/react-table': ^8.20.5
  '@types/node': ^20
  '@types/react': ^19.0.3
  '@types/react-dom': ^19.0.3
  cmdk: ^1.0.4
  dotenv: ^17.2.2
  lucide-react: ^0.542.0
  motion: ^12.23.12
  next: 15.4.7
  postcss: ^8.4.35
  react: ^19.0.0
  react-dom: ^19.0.0
  sonner: ^1.7.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  typescript: ^5.9.2
  vite: ^7.0.6
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  zod: ^4.1.5
