// Generated by scripts/sync-fingerprint.ts — do not edit.
// Resync after any schema or sidecar change:
//   pnpm --filter @codaco/studio-server sync-fingerprint
export const SCHEMA_FINGERPRINT =
  'c470a62a69bcce5888faf8dd2b7e9030e75b3bc6162f3c74cb3cdfc12a1c1287';
