// Generated by scripts/sync-fingerprint.ts — do not edit.
// Resync after any schema or sidecar change:
//   pnpm --filter @codaco/studio-server sync-fingerprint
export const SCHEMA_FINGERPRINT =
  'b146af7900c7e49711e95b6b89c4870806a94b977576219d80fe61b38715e4ec';
