// Generated by scripts/sync-fingerprint.ts — do not edit.
// Resync after any schema or sidecar change:
//   pnpm --filter @codaco/studio-server sync-fingerprint
export const SCHEMA_FINGERPRINT =
  '57a485b67b63682b9007fc2d081e4c448d52dd77bd273c28e3c9e5469ca6e93f';
