REVOKE ALL ON "registry_auth_user", "registry_auth_session", "registry_auth_account", "registry_auth_verification", "registry_auth_rate_limit", "registry_schema_fingerprint", "registry_publishers", "registry_operators", "registry_credentials", "registry_artifacts", "registry_artifact_content", "registry_entries", "registry_audit", "registry_delete_jobs", "registry_reports", "registry_rate_counters" FROM PUBLIC;
  GRANT USAGE ON SCHEMA public TO "registry_app", "registry_operator";
  GRANT SELECT ON registry_schema_fingerprint TO "registry_app", "registry_operator";
  GRANT SELECT, INSERT, UPDATE, DELETE ON "registry_auth_user", "registry_auth_session", "registry_auth_account", "registry_auth_verification", "registry_auth_rate_limit" TO "registry_app";
  GRANT SELECT ON registry_auth_user TO "registry_operator";
  GRANT SELECT ON registry_publishers, registry_operators, registry_credentials, registry_artifacts, registry_artifact_content, registry_entries TO "registry_app", "registry_operator";
  GRANT INSERT (id, user_id, name, orcid) ON registry_publishers TO "registry_app";
  GRANT INSERT (id, publisher_id, token_hash, name, scopes, expires_at) ON registry_credentials TO "registry_app";
  GRANT INSERT (root, raw_hash, byte_size) ON registry_artifacts TO "registry_app";
  GRANT INSERT (id, publisher_id, artifact_root) ON registry_entries TO "registry_app";
  GRANT INSERT (id, entry_id, category, details) ON registry_reports TO "registry_app";
  GRANT INSERT ON registry_artifact_content TO "registry_app";
  GRANT UPDATE (name, orcid) ON registry_publishers TO "registry_app";
  GRANT UPDATE (revoked_at) ON registry_credentials TO "registry_app";
  GRANT UPDATE (yanked_at) ON registry_entries TO "registry_app";
  GRANT UPDATE (suspended_at) ON registry_publishers TO "registry_operator";
  GRANT UPDATE (curated_at) ON registry_entries TO "registry_operator";
  GRANT UPDATE (blocked_at, deleted_at) ON registry_artifacts TO "registry_operator";
  GRANT DELETE ON registry_artifact_content TO "registry_operator";
  GRANT SELECT, INSERT ON registry_audit TO "registry_app", "registry_operator";
  GRANT SELECT, INSERT, UPDATE ON registry_delete_jobs TO "registry_operator";
  GRANT SELECT (root, completed_at) ON registry_delete_jobs TO "registry_app";
  GRANT SELECT, UPDATE (details) ON registry_reports TO "registry_operator";
  GRANT SELECT, INSERT, UPDATE, DELETE ON registry_rate_counters TO "registry_app", "registry_operator";
  GRANT USAGE ON SEQUENCE registry_entries_sequence_seq, registry_reports_sequence_seq TO "registry_app";
  CREATE OR REPLACE FUNCTION registry_reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
  BEGIN RAISE EXCEPTION 'Registry audit is immutable' USING ERRCODE = '42501'; END;
  $$;
  REVOKE ALL ON FUNCTION registry_reject_audit_mutation() FROM PUBLIC;
  DROP TRIGGER IF EXISTS registry_audit_immutable ON registry_audit;
  CREATE TRIGGER registry_audit_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON registry_audit FOR EACH STATEMENT EXECUTE FUNCTION registry_reject_audit_mutation();
GRANT USAGE ON SCHEMA public, registry_migrations TO registry_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public, registry_migrations TO registry_backup;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public, registry_migrations TO registry_backup;
