import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Sidebar from "~/components/Sidebar";
import Header from "~/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full bg-white">
        <body className={inter.className}>
          <div style={{ display: "flex" }}>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <Sidebar />
            </div>
            <main className="flex-1 pl-72 pr-4 bg-gray-900">
              <Header />
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
