import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import sharp from 'sharp';

import {
  DIFF_THRESHOLD,
  DIFF_THRESHOLD_OVERRIDES,
  PIXEL_TOLERANCE,
  type Ratio,
  RATIOS,
  variantFileName,
  WEBP_QUALITY,
} from './config.mts';

export type GeneratedVariant = { w: number; h: number; file: string };

export type GeneratedRatio = {
  ratio: Ratio;
  variants: GeneratedVariant[];
  /** True when the committed files were replaced (or are new). */
  changed: boolean;
};

/** Fraction of pixels whose channels differ by more than PIXEL_TOLERANCE. */
const diffFraction = async (a: Buffer, b: Buffer): Promise<number> => {
  const [rawA, rawB] = await Promise.all(
    [a, b].map((buf) =>
      sharp(buf).ensureAlpha().raw().toBuffer({ resolveWithObject: true }),
    ),
  );
  if (!rawA || !rawB) return 1;
  if (
    rawA.info.width !== rawB.info.width ||
    rawA.info.height !== rawB.info.height
  ) {
    return 1;
  }
  const pa = rawA.data;
  const pb = rawB.data;
  let differing = 0;
  const pixels = rawA.info.width * rawA.info.height;
  for (let i = 0; i < pixels; i++) {
    const o = i * 4;
    if (
      Math.abs((pa[o] ?? 0) - (pb[o] ?? 0)) > PIXEL_TOLERANCE ||
      Math.abs((pa[o + 1] ?? 0) - (pb[o + 1] ?? 0)) > PIXEL_TOLERANCE ||
      Math.abs((pa[o + 2] ?? 0) - (pb[o + 2] ?? 0)) > PIXEL_TOLERANCE
    ) {
      differing++;
    }
  }
  return differing / pixels;
};

/**
 * Derive the shipped WebP variants for one interface × ratio from a PNG
 * master. The replace decision is made once per ratio (on the largest
 * variant) so a set of widths is always internally consistent.
 */
export const processMaster = async (
  assetsDir: string,
  interfaceName: string,
  ratio: Ratio,
  master: Buffer,
): Promise<GeneratedRatio> => {
  await mkdir(assetsDir, { recursive: true });
  const widths = [...RATIOS[ratio].widths].toSorted((x, y) => x - y);
  const threshold = DIFF_THRESHOLD_OVERRIDES[interfaceName] ?? DIFF_THRESHOLD;

  const encoded: Array<GeneratedVariant & { data: Buffer }> = [];
  for (const w of widths) {
    const { data, info } = await sharp(master)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toBuffer({ resolveWithObject: true });
    encoded.push({
      w: info.width,
      h: info.height,
      file: variantFileName(interfaceName, ratio, w),
      data,
    });
  }

  const largest = encoded[encoded.length - 1];
  if (!largest) throw new Error(`No widths configured for ratio ${ratio}`);

  let changed = true;
  const committedLargest = join(assetsDir, largest.file);
  if (existsSync(committedLargest)) {
    const fraction = await diffFraction(
      await readFile(committedLargest),
      largest.data,
    );
    changed = fraction > threshold;
    if (changed) {
      console.log(
        `  ~ ${interfaceName} @ ${ratio}: ${(fraction * 100).toFixed(2)}% pixels changed — updating`,
      );
    }
  }

  // A width set always has all variants present, even on a kept set, in
  // case widths were added to the config since the last generation.
  for (const variant of encoded) {
    const path = join(assetsDir, variant.file);
    if (changed || !existsSync(path)) {
      await writeFile(path, variant.data);
    }
  }

  return {
    ratio,
    variants: encoded.map(({ data: _data, ...variant }) => variant),
    changed,
  };
};

/** Delete committed variants that no longer correspond to any capture. */
export const pruneAssets = async (assetsDir: string, expected: Set<string>) => {
  if (!existsSync(assetsDir)) return;
  for (const file of await readdir(assetsDir)) {
    if (!expected.has(file)) {
      console.log(`  - pruning stale asset ${file}`);
      await unlink(join(assetsDir, file));
    }
  }
};

/** Emit src/generated/manifest.ts. Output is deterministic and stable. */
export const writeManifest = async (
  generatedDir: string,
  results: Map<string, GeneratedRatio[]>,
) => {
  const interfaces = [...results.keys()].toSorted();
  const lines: string[] = [
    '// GENERATED by `pnpm --filter @codaco/interface-images generate` — do not edit.',
    '// Regenerate via `pnpm generate:interface-images` at the repo root.',
    "import type { ManifestEntry } from '../types';",
    '',
    'const manifest = {',
  ];
  for (const name of interfaces) {
    lines.push(`  ${name}: {`);
    const ratios = results.get(name) ?? [];
    for (const { ratio, variants } of ratios) {
      lines.push(`    '${ratio}': {`);
      lines.push('      variants: [');
      for (const v of variants) {
        lines.push(
          `        { w: ${v.w}, h: ${v.h}, url: new URL('./assets/${v.file}', import.meta.url).href },`,
        );
      }
      lines.push('      ],');
      lines.push('    },');
    }
    lines.push('  },');
  }
  lines.push('} satisfies Record<string, ManifestEntry>;');
  lines.push('');
  lines.push('export type InterfaceType = keyof typeof manifest;');
  lines.push('');
  lines.push('export default manifest;');
  lines.push('');
  await mkdir(generatedDir, { recursive: true });
  await writeFile(join(generatedDir, 'manifest.ts'), lines.join('\n'));
};
