import { existsSync } from 'node:fs';
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import sharp from 'sharp';

import {
  type Ratio,
  RATIOS,
  variantFileName,
  WEBP_QUALITY,
} from './config.mts';

export type GeneratedVariant = { w: number; h: number; file: string };

export type GeneratedRatio = {
  ratio: Ratio;
  variants: GeneratedVariant[];
};

/**
 * Derive the committed WebP variants for one interface × ratio from a PNG
 * master. Every variant is rewritten so a completed generation pass is a
 * self-contained refresh of the shipped image set.
 */
export const processMaster = async (
  assetsDir: string,
  interfaceName: string,
  ratio: Ratio,
  master: Buffer,
): Promise<GeneratedRatio> => {
  await mkdir(assetsDir, { recursive: true });
  const widths = [...RATIOS[ratio].widths].toSorted((x, y) => x - y);

  const encoded: GeneratedVariant[] = [];
  for (const w of widths) {
    const { data, info } = await sharp(master)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toBuffer({ resolveWithObject: true });
    // Name files by the ENCODED width: withoutEnlargement may clamp below the
    // requested width, and several requested widths can clamp to the same
    // size — filenames and manifest entries must describe the file that
    // actually exists.
    if (encoded.some((variant) => variant.w === info.width)) continue;
    const file = variantFileName(interfaceName, ratio, info.width);
    await writeFile(join(assetsDir, file), data);
    encoded.push({ w: info.width, h: info.height, file });
  }

  if (encoded.length === 0) {
    throw new Error(`No widths configured for ratio ${ratio}`);
  }

  return { ratio, variants: encoded };
};

/** Delete committed variants that no longer correspond to any capture. */
export const pruneAssets = async (assetsDir: string, expected: Set<string>) => {
  if (!existsSync(assetsDir)) return;
  for (const file of await readdir(assetsDir)) {
    if (!expected.has(file)) {
      console.log(`  - pruning stale asset ${file}`);
      await unlink(join(assetsDir, file));
    }
  }
};

/** Emit src/generated/manifest.ts. Output is deterministic and stable. */
export const writeManifest = async (
  generatedDir: string,
  results: Map<string, GeneratedRatio[]>,
) => {
  const interfaces = [...results.keys()].toSorted();
  const lines: string[] = [
    '// GENERATED by `pnpm --filter @codaco/interface-images generate` — do not edit.',
    '// Regenerate via `pnpm generate:interface-images` at the repo root.',
    "import type { ManifestEntry } from '../types';",
    '',
    'const manifest = {',
  ];
  for (const name of interfaces) {
    lines.push(`  ${name}: {`);
    const ratios = results.get(name) ?? [];
    for (const { ratio, variants } of ratios) {
      lines.push(`    '${ratio}': {`);
      lines.push('      variants: [');
      for (const v of variants) {
        lines.push(
          `        { w: ${v.w}, h: ${v.h}, url: new URL('./assets/${v.file}', import.meta.url).href },`,
        );
      }
      lines.push('      ],');
      lines.push('    },');
    }
    lines.push('  },');
  }
  lines.push('} satisfies Record<string, ManifestEntry>;');
  lines.push('');
  lines.push('export type InterfaceType = keyof typeof manifest;');
  lines.push('');
  lines.push('export default manifest;');
  lines.push('');
  await mkdir(generatedDir, { recursive: true });
  await writeFile(join(generatedDir, 'manifest.ts'), lines.join('\n'));
};
