/**
 * Canonical per-interface option-key inventory for the e2e matrix.
 * Keys are free-form but stable; the coverage manifest test (a) checks every
 * key here is claimed by >=1 scenario's `covers` (or by the shared
 * cross-cutting suite via shared-claims.ts), and (b) walks each stage
 * schema's top-level and prompt-level Zod keys to catch schema options
 * missing from this inventory entirely.
 */
export const OPTION_INVENTORY: Record<string, readonly string[]> = {
  CategoricalBin: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'filter',
    'prompts[].id',
    'prompts[].text',
    'prompts[].variable',
    'prompts[].otherVariable',
    'prompts[].otherVariablePrompt',
    'prompts[].otherOptionLabel',
    'prompts[].bucketSortOrder',
    'prompts[].bucketSortOrder=*',
    'prompts[].binSortOrder',
    'codebook:variable-options',
    'codebook:node-label-and-type',
    'drop-writes-single-value-array',
    're-bin-replaces-value',
    'other-dialog-submit-writes-other-clears-variable',
    'other-dialog-cancel-noop',
    'regular-bin-drop-clears-other-variable',
    'other-option-label-without-other-variable-dead-config',
    'multi-value-membership',
    'empty-array-treated-as-unset',
    'ready-for-next-pulse',
    'bin-expand-collapse',
    'duplicate-option-labels-index-keyed',
    'category-color-cycling',
  ],
  AlterForm: [
    'label',
    'interviewScript',
    'skipLogic',
    'filter',
    'subject',
    'introductionPanel',
    'form',
    'form.fields[].variable',
    'form.fields[].prompt',
    'form.fields[].hint',
    'form.fields[].showValidationHints',
    'variable.component',
    'variable.type',
    'variable.options',
    'variable.validation.required',
    'variable.validation.minLength',
    'variable.validation.maxLength',
    'variable.validation.minValue',
    'variable.validation.maxValue',
    'variable.validation.minSelected',
    'variable.validation.maxSelected',
    'variable.validation.unique',
    'variable.validation.sameAs',
    'variable.validation.differentFrom',
    'variable.validation.greaterThanVariable',
    'variable.validation.greaterThanOrEqualToVariable',
    'variable.validation.lessThanVariable',
    'variable.validation.lessThanOrEqualToVariable',
    'variable.parameters.vas',
    'variable.parameters.datePicker',
    'variable.parameters.relativeDatePicker',
    'variable.encrypted',
    'codebook.nodeType.colorAndShape',
    'backNav.discardDialog',
    'backNav.autosave',
    'emptyItemShortCircuit',
    'readyStateScrollGating',
  ],
  AlterEdgeForm: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'filter',
    'introductionPanel.title',
    'introductionPanel.text',
    'form',
    'form.fields[].variable',
    'form.fields[].prompt',
    'form.fields[].hint',
    'form.fields[].showValidationHints',
    'form.fields[].id',
    'variable.component=Text',
    'variable.component=TextArea',
    'variable.component=Number',
    'variable.component=Boolean',
    'variable.options(boolean)+negative',
    'variable.component=Toggle',
    'variable.component=RadioGroup',
    'variable.component=LikertScale',
    'variable.component=CheckboxGroup',
    'variable.component=ToggleButtonGroup',
    'variable.options(ordinal/categorical)',
    'useColumns auto-layout (>6 options)',
    'variable.component=VisualAnalogScale',
    'variable.parameters(VAS minLabel/maxLabel)',
    'variable.component=DatePicker',
    'variable.parameters(DatePicker type/min/max)',
    'variable.component=RelativeDatePicker',
    'variable.parameters(RelativeDatePicker anchor/before/after)',
    'variable.validation.required',
    'variable.validation.minLength/maxLength',
    'variable.validation.minValue/maxValue',
    'variable.validation.minSelected/maxSelected',
    'variable.validation.unique',
    'variable.validation.sameAs/differentFrom',
    'variable.validation.greaterThanVariable/lessThanVariable/etc',
    'codebook.edge[type].color',
    'codebook.node[type].color/shape/labelVariable',
    'zero-edges auto-skip',
    'multi-slide iteration + per-edge persistence',
    'backwards navigation (intro/slide)',
    'backwards valid-dirty auto-submit',
    'backwards invalid-dirty discard dialog',
    'ready-for-next scroll-to-bottom gating',
    'initial values from existing edge attributes',
    'form title absence (TitlelessFormSchema)',
  ],
  Anonymisation: [
    'explanationText.title',
    'explanationText.body',
    'label',
    'interviewScript',
    'skipLogic',
    'validation.minLength',
    'validation.maxLength',
    'passphraseFields.required',
    'confirmField.sameAs',
    'beforeNext.gating',
    'beforeNext.backwardsAllowed',
    'passphrase.persistOnRevisit',
    'passwordField.showToggle',
    'experiments.encryptedVariables=true+encryptedVariable',
    'experiments.encryptedVariables=absent',
    'encryptedVariable.missingPassphrase.prompter',
    'encryptedVariable.wrongPassphrase.invalid',
  ],
  DyadCensus: [
    'label',
    'interviewScript',
    'skipLogic',
    'filter',
    'subject.type',
    'introductionPanel',
    'prompts[].id',
    'prompts[].text',
    'prompts[].createEdge=yes-path',
    'prompts[].createEdge=no-path',
    'prompts[].createEdge=toggle-idempotence',
    'prompts[].createEdge=shared-prefill',
    'prompts=multi-cycling',
    'answer-required-validation',
    'pair-enumeration',
    'backwards-navigation',
    'zero-pairs-force-skip',
    'codebook.edge.color',
    'codebook.node.color-shape',
  ],
  EgoForm: [
    'introductionPanel.title',
    'introductionPanel.text',
    'form.fields-ordering-and-prompt',
    'form.fields[].hint',
    'form.fields[].showValidationHints',
    'form.fields[].id', // dead: Architect reorder key only, ignored at runtime
    'component=Text',
    'component=TextArea',
    'component=Number',
    'component=VisualAnalogScale',
    'component=Boolean',
    'component=Toggle',
    'component=RadioGroup',
    'component=LikertScale',
    'component=CheckboxGroup',
    'component=ToggleButtonGroup',
    'component=DatePicker',
    'DatePicker.parameters(type/min/max)',
    'component=RelativeDatePicker',
    'RelativeDatePicker.parameters(anchor/before/after)-range-validation',
    'egoVariable.readOnly', // dead: Architect editors only
    'egoVariable.name-fallback-label', // dead: prompt is required, fallback unreachable
    'RadioGroup-auto-columns->6-options',
    'Boolean-custom-options',
    'Boolean-options[].negative', // dead: Boolean.tsx never reads it
    'validation.required',
    'validation.requiredAcceptsNull', // dead: declared, consumed nowhere
    'validation.minLength/maxLength',
    'validation.minValue/maxValue',
    'validation.minSelected/maxSelected',
    'validation.sameAs',
    'validation.differentFrom',
    'validation.greaterThanVariable-family',
    'showValidationHints-summary',
    'pre-population-from-ego-attributes',
    'backwards-nav-discard-and-autosubmit',
    'ready-for-next-pulse',
    'scroll-nudge-15s-inactivity',
    'label', // dead: author-facing only, never rendered
    'interviewScript', // dead: author-facing only, never rendered
    'skipLogic',
  ],
  OrdinalBin: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'filter',
    'prompts[].id',
    'prompts[].text',
    'prompts[].variable',
    'prompts[].bucketSortOrder',
    'prompts[].binSortOrder',
    'prompts[].color',
    'codebook.ordinalOptions',
  ],
  NameGenerator: [
    'subject',
    'form',
    'form.title',
    'form.fields[].variable',
    'form.fields[].prompt',
    'form.fields[].hint',
    'form.fields[].showValidationHints',
    'form.fields[].id',
    'codebook: variable.component',
    'codebook: variable.validation',
    'codebook: variable.parameters',
    'codebook: variable.encrypted',
    'codebook: node.icon / node.color / node.shape',
    'prompts[].id',
    'prompts[].text',
    'prompts[].additionalAttributes',
    'behaviours',
    'behaviours.minNodes',
    'behaviours.maxNodes',
    'panels[].id',
    'panels[].title',
    'panels[].dataSource=existing',
    'panels[].dataSource=asset(external)',
    'panels[].filter',
    'label',
    'interviewScript',
    'skipLogic',
  ],
  NetworkComposer: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'quickAdd',
    'layoutVariable',
    'nodeForm.present',
    'nodeForm.absent',
    'convexHullVariable.tapToggle',
    'convexHullVariable.lasso',
    'convexHullVariable.unset',
    'background.image', // dead config
    'background.concentricCircles',
    'background.skewedTowardCenter',
    'behaviours.automaticLayout',
    'behaviours.automaticLayout.absent',
    'edges[]',
    'edges[].absent',
    'edges[].multipleTypes',
    'edges[].form',
    'fields[].component',
    'fields[].component.overridesCodebook',
    'fields[].parameters',
    'fields[].label',
    'fields[].hint',
    'fields[].showValidationHints',
    'codebook.validationGatesAutosave',
    'codebook.nodeEdgeColorAndName',
    'hullVariable.categoricalOptions',
    'implicit.undoRedo',
    'implicit.deleteMultiSelect',
    'implicit.drawerDeselect',
  ],
  Narrative: [
    'label',
    'interviewScript',
    'subject',
    'presets[].id',
    'presets[].label',
    'presets[].layoutVariable',
    'presets[].groupVariable',
    'presets[].edges.display',
    'presets[].highlight',
    'background.concentricCircles',
    'background.skewedTowardCenter',
    'behaviours.automaticLayout',
    'behaviours.allowRepositioning',
    'behaviours.freeDraw',
    'filter',
    'skipLogic',
  ],
  OneToManyDyadCensus: [
    'subject.type',
    'behaviours.removeAfterConsideration',
    'prompts (array length > 1)',
    'prompts[].createEdge',
    'prompts[].bucketSortOrder',
    'prompts[].binSortOrder',
    'prompts[].text',
    'label',
    'interviewScript',
    'filter',
    'skipLogic',
  ],
  Sociogram: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'filter',
    'background.image',
    'background.concentricCircles',
    'background.skewedTowardCenter',
    'behaviours.automaticLayout',
    'behaviours.allowRepositioning',
    'behaviours.freeDraw',
    'prompts[].id',
    'prompts[].text',
    'prompts[].layout.layoutVariable',
    'prompts[].sortOrder',
    'prompts[].edges.display',
    'prompts[].edges.create',
    'prompts[].highlight.allowHighlighting',
    'prompts[].highlight.variable',
  ],
  TieStrengthCensus: [
    'label',
    'interviewScript',
    'skipLogic',
    'filter',
    'subject.type',
    'introductionPanel',
    'prompts[].text',
    'prompts[].createEdge',
    'prompts[].edgeVariable',
    'prompts[].negativeLabel',
    'prompts[].multiple',
    'codebook.edge.variable.options',
    'codebook.edge.color',
    'auto-advance-timing',
    'response-required-validation',
    'backwards-navigation',
    'pre-selection',
    'sibling-prompt-scoping',
    'stage-completion',
  ],
  NameGeneratorRoster: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'dataSource',
    'dataSource=csv',
    'dataSource=error',
    'cardOptions',
    'cardOptions.additionalProperties',
    'sortOptions',
    'sortOptions.sortOrder',
    'sortOptions.sortOrder=*',
    'sortOptions.sortableProperties',
    'searchOptions',
    'searchOptions.fuzziness',
    'searchOptions.matchProperties',
    'searchOptions.matchProperties=empty',
    'behaviours',
    'behaviours.minNodes',
    'behaviours.maxNodes',
    'prompts[].id',
    'prompts[].text',
    'prompts[].additionalAttributes',
    'remove-node-round-trip',
    'encrypted-variable-passphrase-gate',
    'label-fallback-heuristic',
  ],
  NameGeneratorQuickAdd: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject.type',
    'quickAdd',
    'behaviours.minNodes',
    'behaviours.maxNodes',
    'behaviours.maxNodes-panel-drag-gap',
    'panels[].id',
    'panels[].title',
    'panels[].dataSource=existing',
    'panels[].dataSource=assetId',
    'panels[].filter',
    'prompts[].id',
    'prompts[].text',
    'prompts[].additionalAttributes',
    'codebook.node.color',
    'codebook.node.icon',
    'codebook.node.shape',
    'codebook.variables.quickAdd.encrypted',
  ],
  FamilyPedigree: [
    'label',
    'interviewScript',
    'skipLogic',
    'nodeConfig.type',
    'nodeConfig.nodeLabelVariable',
    'nodeConfig.nodeLabelVariable=unset-name-fallback',
    'nodeConfig.egoVariable',
    'nodeConfig.relationshipVariable',
    'nodeConfig.biologicalSexVariable',
    'nodeConfig.form',
    'nodeConfig.form[].hint',
    'nodeConfig.form[].showValidationHints',
    'edgeConfig.type',
    'edgeConfig.relationshipTypeVariable',
    'edgeConfig.relationshipTypeVariable=adoptive',
    'edgeConfig.relationshipTypeVariable=social',
    'edgeConfig.isActiveVariable',
    'edgeConfig.isGestationalCarrierVariable',
    'edgeConfig.isGestationalCarrierVariable=true-surrogate',
    'edgeConfig.gameteRoleVariable',
    'edgeConfig.gameteRoleVariable=donor-both',
    'framing=fixed(gamete)',
    'framing=fixed(gendered)',
    'framing=participantChoice',
    'boundaries.requireGrandparents=required',
    'boundaries.requireGrandparents=recommended',
    'boundaries.requireGrandparents=off',
    'boundaries.requireChildrenContributors=required',
    'introScreen',
    'introScreen.items[].type=text',
    'introScreen.items[].type=asset',
    'censusPrompt',
    'nominationPrompts=absent',
    'nominationPrompts[].text',
    'nominationPrompts[].variable',
    'nominationPrompts[].id',
  ],
  FinishSession: [
    // Synthetic, engine-appended stage — not schema-8, not protocol-authorable.
    'stage.type',
    'stage.id',
    'stage.label', // dead: DefaultFinishStage.label is set but never rendered
    'confirm-dialog.copy',
    'confirm-dialog.destructive-focus',
    'onFinish.confirm-calls-handler',
    'onFinish.cancel-path',
    'onFinish.pending-state',
    'onFinish.error-retry',
    'onFinish.abort-on-dismiss',
    'interviewId-guard', // dead: unreachable e2e, host always seeds session.id
    'terminal-navigation',
    'progress-100',
    'stagesMenu-exclusion',
    'back-navigation-network-intact',
    'analytics.interview_finished', // dead e2e: host sets disableAnalytics=true
    // NOTE: no `skipLogic` — FinishSession is engine-appended, has no schema-8
    // definition, and is absent from the stageSchema union, so an author cannot
    // attach skipLogic to it (and semantically you cannot skip the finish).
    // stage-config-schema-support.test.ts enforces this.
  ],
  Geospatial: [
    'label',
    'interviewScript',
    'skipLogic',
    'subject',
    'filter',
    'mapOptions.tokenAssetId',
    'mapOptions.style',
    'mapOptions.center',
    'mapOptions.initialZoom',
    'mapOptions.dataSourceAssetId',
    'mapOptions.color',
    'mapOptions.color=default',
    'mapOptions.targetFeatureProperty',
    'mapOptions.showTransit',
    'mapOptions.showTransit=false',
    'mapOptions.allowSearch',
    'mapOptions.allowSearch=false',
    'prompts[].id',
    'prompts[].text',
    'prompts[].variable',
    'outside-selectable-areas',
    'map-click-outside-features',
    'node-stepping-beforeNext',
    'selection-restore',
    'empty-stage-passthrough',
    'stub-mode-contract',
    'map-error-overlay',
    'offline-indicator',
    'analytics-events',
  ],
  Information: [
    'title',
    'items[].type=text',
    'items[].type=asset(image)',
    'items[].type=asset(audio)',
    'items[].type=asset(video)',
    'items[].size',
    'items[].description',
    'items-ordering',
    'items=[]',
    'title-empty',
    'markdown-allowlist',
    'external-links',
    'missing-asset-fallback',
    'unsupported-asset-fallback',
    'label',
    'interviewScript',
    'skipLogic',
  ],
  NarrativePedigree: [
    'type',
    'id',
    'label',
    'interviewScript',
    'skipLogic',
    'sourceStageId',
    'sourceStageId.membershipScoping',
    'sourceStageId.misconfigured',
    'showAtRiskStatuses=false',
    'showAtRiskStatuses=true',
    'diseases',
    'diseases[].id',
    'diseases[].label',
    'diseases[].color',
    'diseases[].variable',
    'diseases[].inheritancePattern=autosomalDominant',
    'diseases[].inheritancePattern=autosomalRecessive',
    'diseases[].inheritancePattern=xLinkedRecessive',
    'diseases[].inheritancePattern=xLinkedDominant',
    'diseases[].inheritancePattern=yLinked',
    'diseases[].inheritancePattern=mitochondrial',
    'diseases[].inheritancePattern=multifactorial',
    'diseases[].inheritancePattern=unknown',
    'focalHighlighting',
    'focalAffordanceDisabled',
    'zoomControls',
    'saveSnapshot',
    'readOnlyInvariant',
  ],
};
