// CLDR 47 English names and autonyms, used only when the runtime's Intl data
// has none. Chromium (and so Electron and Chrome) ships trimmed ICU data.
// An entry has no autonym where CLDR has no locale data for the language.
// `tw` is left out: CLDR names it "Akan", the same as `ak`.
export const LANGUAGE_NAMES: Readonly<
  Record<string, readonly [englishName: string, autonym?: string]>
> = {
  aa: ['Afar'],
  ab: ['Abkhazian'],
  ae: ['Avestan'],
  af: ['Afrikaans', 'Afrikaans'],
  ak: ['Akan', 'Akan'],
  am: ['Amharic', 'አማርኛ'],
  an: ['Aragonese'],
  ar: ['Arabic', 'العربية'],
  as: ['Assamese', 'অসমীয়া'],
  av: ['Avaric'],
  ay: ['Aymara'],
  az: ['Azerbaijani', 'azərbaycan'],
  ba: ['Bashkir'],
  be: ['Belarusian', 'беларуская'],
  bg: ['Bulgarian', 'български'],
  bi: ['Bislama'],
  bm: ['Bambara', 'bamanakan'],
  bn: ['Bangla', 'বাংলা'],
  bo: ['Tibetan', 'བོད་སྐད་'],
  br: ['Breton', 'brezhoneg'],
  bs: ['Bosnian', 'bosanski'],
  ca: ['Catalan', 'català'],
  ce: ['Chechen', 'нохчийн'],
  ch: ['Chamorro'],
  co: ['Corsican'],
  cr: ['Cree'],
  cs: ['Czech', 'čeština'],
  cu: ['Church Slavic'],
  cv: ['Chuvash', 'чӑваш'],
  cy: ['Welsh', 'Cymraeg'],
  da: ['Danish', 'dansk'],
  de: ['German', 'Deutsch'],
  dv: ['Divehi'],
  dz: ['Dzongkha', 'རྫོང་ཁ'],
  ee: ['Ewe', 'eʋegbe'],
  el: ['Greek', 'Ελληνικά'],
  en: ['English', 'English'],
  eo: ['Esperanto', 'Esperanto'],
  es: ['Spanish', 'español'],
  et: ['Estonian', 'eesti'],
  eu: ['Basque', 'euskara'],
  fa: ['Persian', 'فارسی'],
  ff: ['Fula', 'Pulaar'],
  fi: ['Finnish', 'suomi'],
  fj: ['Fijian'],
  fo: ['Faroese', 'føroyskt'],
  fr: ['French', 'français'],
  fy: ['Western Frisian', 'Frysk'],
  ga: ['Irish', 'Gaeilge'],
  gd: ['Scottish Gaelic', 'Gàidhlig'],
  gl: ['Galician', 'galego'],
  gn: ['Guarani'],
  gu: ['Gujarati', 'ગુજરાતી'],
  gv: ['Manx', 'Gaelg'],
  ha: ['Hausa', 'Hausa'],
  he: ['Hebrew', 'עברית'],
  hi: ['Hindi', 'हिन्दी'],
  ho: ['Hiri Motu'],
  hr: ['Croatian', 'hrvatski'],
  ht: ['Haitian Creole'],
  hu: ['Hungarian', 'magyar'],
  hy: ['Armenian', 'հայերեն'],
  hz: ['Herero'],
  ia: ['Interlingua', 'interlingua'],
  id: ['Indonesian', 'Indonesia'],
  ie: ['Interlingue', 'Interlingue'],
  ig: ['Igbo', 'Igbo'],
  ii: ['Sichuan Yi', 'ꆈꌠꉙ'],
  ik: ['Inupiaq'],
  io: ['Ido'],
  is: ['Icelandic', 'íslenska'],
  it: ['Italian', 'italiano'],
  iu: ['Inuktitut'],
  ja: ['Japanese', '日本語'],
  jv: ['Javanese', 'Jawa'],
  ka: ['Georgian', 'ქართული'],
  kg: ['Kongo'],
  ki: ['Kikuyu', 'Gikuyu'],
  kj: ['Kuanyama'],
  kk: ['Kazakh', 'қазақ тілі'],
  kl: ['Kalaallisut', 'kalaallisut'],
  km: ['Khmer', 'ខ្មែរ'],
  kn: ['Kannada', 'ಕನ್ನಡ'],
  ko: ['Korean', '한국어'],
  kr: ['Kanuri'],
  ks: ['Kashmiri', 'کٲشُر'],
  ku: ['Kurdish', 'kurdî (kurmancî)'],
  kv: ['Komi'],
  kw: ['Cornish', 'kernewek'],
  ky: ['Kyrgyz', 'кыргызча'],
  la: ['Latin'],
  lb: ['Luxembourgish', 'Lëtzebuergesch'],
  lg: ['Ganda', 'Luganda'],
  li: ['Limburgish'],
  ln: ['Lingala', 'lingála'],
  lo: ['Lao', 'ລາວ'],
  lt: ['Lithuanian', 'lietuvių'],
  lu: ['Luba-Katanga', 'Tshiluba'],
  lv: ['Latvian', 'latviešu'],
  mg: ['Malagasy', 'Malagasy'],
  mh: ['Marshallese'],
  mi: ['Māori', 'Māori'],
  mk: ['Macedonian', 'македонски'],
  ml: ['Malayalam', 'മലയാളം'],
  mn: ['Mongolian', 'монгол'],
  mr: ['Marathi', 'मराठी'],
  ms: ['Malay', 'Melayu'],
  mt: ['Maltese', 'Malti'],
  my: ['Burmese', 'မြန်မာ'],
  na: ['Nauru'],
  nb: ['Norwegian Bokmål', 'norsk bokmål'],
  nd: ['North Ndebele', 'isiNdebele'],
  ne: ['Nepali', 'नेपाली'],
  ng: ['Ndonga'],
  nl: ['Dutch', 'Nederlands'],
  nn: ['Norwegian Nynorsk', 'norsk nynorsk'],
  no: ['Norwegian', 'norsk'],
  nr: ['South Ndebele'],
  nv: ['Navajo'],
  ny: ['Nyanja'],
  oc: ['Occitan', 'occitan'],
  oj: ['Ojibwa'],
  om: ['Oromo', 'Oromoo'],
  or: ['Odia', 'ଓଡ଼ିଆ'],
  os: ['Ossetic', 'ирон'],
  pa: ['Punjabi', 'ਪੰਜਾਬੀ'],
  pi: ['Pali'],
  pl: ['Polish', 'polski'],
  ps: ['Pashto', 'پښتو'],
  pt: ['Portuguese', 'português'],
  qu: ['Quechua', 'Runasimi'],
  rm: ['Romansh', 'rumantsch'],
  rn: ['Rundi', 'Ikirundi'],
  ro: ['Romanian', 'română'],
  ru: ['Russian', 'русский'],
  rw: ['Kinyarwanda', 'Ikinyarwanda'],
  sa: ['Sanskrit', 'संस्कृत भाषा'],
  sc: ['Sardinian', 'sardu'],
  sd: ['Sindhi', 'سنڌي'],
  se: ['Northern Sami', 'davvisámegiella'],
  sg: ['Sango', 'Sängö'],
  si: ['Sinhala', 'සිංහල'],
  sk: ['Slovak', 'slovenčina'],
  sl: ['Slovenian', 'slovenščina'],
  sm: ['Samoan'],
  sn: ['Shona', 'chiShona'],
  so: ['Somali', 'Soomaali'],
  sq: ['Albanian', 'shqip'],
  sr: ['Serbian', 'српски'],
  ss: ['Swati'],
  st: ['Southern Sotho', 'Sesotho'],
  su: ['Sundanese', 'Basa Sunda'],
  sv: ['Swedish', 'svenska'],
  sw: ['Swahili', 'Kiswahili'],
  ta: ['Tamil', 'தமிழ்'],
  te: ['Telugu', 'తెలుగు'],
  tg: ['Tajik', 'тоҷикӣ'],
  th: ['Thai', 'ไทย'],
  ti: ['Tigrinya', 'ትግርኛ'],
  tk: ['Turkmen', 'türkmen dili'],
  tl: ['Filipino'],
  tn: ['Tswana', 'Setswana'],
  to: ['Tongan', 'lea fakatonga'],
  tr: ['Turkish', 'Türkçe'],
  ts: ['Tsonga'],
  tt: ['Tatar', 'татар'],
  ty: ['Tahitian'],
  ug: ['Uyghur', 'ئۇيغۇرچە'],
  uk: ['Ukrainian', 'українська'],
  ur: ['Urdu', 'اردو'],
  uz: ['Uzbek', 'o‘zbek'],
  ve: ['Venda'],
  vi: ['Vietnamese', 'Tiếng Việt'],
  vo: ['Volapük'],
  wa: ['Walloon'],
  wo: ['Wolof', 'Wolof'],
  xh: ['Xhosa', 'IsiXhosa'],
  yi: ['Yiddish', 'ייִדיש'],
  yo: ['Yoruba', 'Èdè Yorùbá'],
  za: ['Zhuang', 'Vahcuengh'],
  zh: ['Chinese', '中文'],
  zu: ['Zulu', 'isiZulu'],
};
