export const REGISTRY_OPERATIONAL_DIAGNOSTICS = Object.freeze([
  'REGISTRY_AUTH_DIAGNOSTIC',
  'REGISTRY_AUTH_REQUEST_FAILURE',
  'REGISTRY_AUTH_SESSION_FAILURE',
  'REGISTRY_CONFIGURATION_INVALID',
  'REGISTRY_STARTUP_FAILED',
  'REGISTRY_PROCESS_FAILED',
  'REGISTRY_DATABASE_IDLE_ERROR',
  'REGISTRY_REQUEST_FAILED',
  'REGISTRY_READINESS_FAILED',
  'REGISTRY_CLEANUP_FAILED',
  'REGISTRY_LISTENING',
  'REGISTRY_SHUTDOWN_COMPLETE',
  'REGISTRY_SHUTDOWN_FAILED',
  'REGISTRY_MIGRATION_COMPLETE',
  'REGISTRY_MIGRATION_FAILED',
  'REGISTRY_OPERATOR_COMPLETE',
  'REGISTRY_OPERATOR_FAILED',
  'REGISTRY_BACKUP_VERIFIED',
  'REGISTRY_BACKUP_FAILED',
  'REGISTRY_RECOVERY_RECONCILED',
  'REGISTRY_RECOVERY_FAILED',
] as const);

export type RegistryOperationalDiagnostic =
  (typeof REGISTRY_OPERATIONAL_DIAGNOSTICS)[number];
