-- 0002_studio_multi_replica_sync: generated by migrate:generate from 0001_initial.
CREATE TABLE "protocol_connections" (
	"team_id" text NOT NULL,
	"draft_id" uuid,
	"connection_id" text,
	"socket_id" text,
	"kind" text NOT NULL,
	"owner" text NOT NULL,
	"user_id" text NOT NULL,
	"display_name" text NOT NULL,
	"mode" text NOT NULL,
	"section_id" text,
	"replica_id" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT "protocol_connections_pkey" PRIMARY KEY("draft_id","connection_id"),
	CONSTRAINT "protocol_connections_kind_check" CHECK ("kind" IN ('socket', 'contact')),
	CONSTRAINT "protocol_connections_mode_check" CHECK ("mode" IN ('viewing', 'editing')),
	CONSTRAINT "protocol_connections_socket_id_check" CHECK (("kind" = 'socket') = ("socket_id" IS NOT NULL)),
	CONSTRAINT "protocol_connections_connection_id_check" CHECK (char_length("connection_id") BETWEEN 1 AND 512)
);


ALTER TABLE "protocol_connections" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "protocol_staged_resources" (
	"team_id" text NOT NULL,
	"draft_id" uuid,
	"owner" text,
	"edit_id" text,
	"resource_id" text,
	"request_id" text NOT NULL,
	"kind" text NOT NULL,
	"descriptor" jsonb NOT NULL,
	"object_key" text,
	"content_hash" text,
	"byte_length" integer,
	"content_type" text,
	"secret_ciphertext" bytea,
	"secret_key_id" text,
	"created_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT "protocol_staged_resources_pkey" PRIMARY KEY("draft_id","owner","edit_id","resource_id"),
	CONSTRAINT "protocol_staged_resources_request_key" UNIQUE("draft_id","owner","edit_id","kind","request_id"),
	CONSTRAINT "protocol_staged_resources_kind_check" CHECK ("kind" IN ('content', 'secret')),
	CONSTRAINT "protocol_staged_resources_storage_check" CHECK (("object_key" IS NULL) <> ("secret_ciphertext" IS NULL)),
	CONSTRAINT "protocol_staged_resources_secret_key_check" CHECK (("secret_key_id" IS NULL) = ("secret_ciphertext" IS NULL))
);


ALTER TABLE "protocol_staged_resources" ENABLE ROW LEVEL SECURITY;

CREATE INDEX "protocol_events_draft_id_section_id_cursor_lock_idx" ON "protocol_events" ("draft_id","section_id","cursor" DESC NULLS LAST) WHERE "kind" = 'lock';

CREATE INDEX "protocol_connections_team_id_draft_id_owner_expires_at_idx" ON "protocol_connections" ("team_id","draft_id","owner","expires_at");

CREATE INDEX "protocol_connections_draft_id_socket_id_idx" ON "protocol_connections" ("draft_id","socket_id");

CREATE INDEX "protocol_connections_expires_at_idx" ON "protocol_connections" ("expires_at");

CREATE INDEX "protocol_connections_draft_id_expires_at_socket_idx" ON "protocol_connections" ("draft_id","expires_at") WHERE "kind" = 'socket';

CREATE INDEX "protocol_staged_resources_team_id_created_at_idx" ON "protocol_staged_resources" ("team_id","created_at");

ALTER TABLE "protocol_connections" ADD CONSTRAINT "protocol_connections_draft_id_team_id_drafts_id_team_id_fkey" FOREIGN KEY ("draft_id","team_id") REFERENCES "drafts"("id","team_id") ON DELETE CASCADE;

ALTER TABLE "protocol_staged_resources" ADD CONSTRAINT "protocol_staged_resources_8KVb58hmJSP2_fkey" FOREIGN KEY ("draft_id","team_id") REFERENCES "drafts"("id","team_id") ON DELETE CASCADE;

CREATE POLICY "team_isolation" ON "protocol_connections" AS PERMISSIVE FOR ALL TO public USING (team_id = NULLIF(current_setting('app.team_id', true), '') OR current_user = 'studio_maintenance') WITH CHECK (team_id = NULLIF(current_setting('app.team_id', true), '') OR current_user = 'studio_maintenance');

CREATE POLICY "team_isolation" ON "protocol_staged_resources" AS PERMISSIVE FOR ALL TO public USING (team_id = NULLIF(current_setting('app.team_id', true), '') OR current_user = 'studio_maintenance') WITH CHECK (team_id = NULLIF(current_setting('app.team_id', true), '') OR current_user = 'studio_maintenance');
