export const MAX_UPLOAD_BYTES = 100 * 1024 * 1024;

const ENVELOPE_BYTES = 1024 * 1024;

export const MAX_SOCKET_FRAME_BYTES = MAX_UPLOAD_BYTES + ENVELOPE_BYTES;

export const MAX_UNARY_BODY_BYTES =
  4 * Math.ceil(MAX_UPLOAD_BYTES / 3) + ENVELOPE_BYTES;
