-- 0005_session_finish: generated by migrate:generate from 0004_job_correlation.
ALTER TABLE "interview_sessions" ADD COLUMN "finish_stage_id" text;

ALTER TABLE "interview_sessions" ADD COLUMN "finish_outcome" text;

ALTER TABLE "interview_sessions" ADD CONSTRAINT "interview_sessions_finish_check" CHECK (("finish_stage_id" IS NULL) = ("finish_outcome" IS NULL)
          AND ("finish_stage_id" IS NULL OR (
            "status" = 'completed'
            AND char_length("finish_stage_id") BETWEEN 1 AND 128
            AND "finish_outcome" IN ('completed', 'ineligible', 'terminated'))));
