// Generated by scripts/sync-fingerprint.ts — do not edit.
// Resync after any schema or sidecar change:
//   pnpm --filter @codaco/studio-api sync-fingerprint
export const SCHEMA_FINGERPRINT =
  '6540ad67941dd5a4ff0cd957ff82fc51952fa76085090f0448ad5b5a6c90173d';
