// Generated by scripts/sync-fingerprint.ts — do not edit.
// Resync after any schema or sidecar change:
//   pnpm --filter @codaco/studio-api sync-fingerprint
export const SCHEMA_FINGERPRINT =
  'ef5c73ec1c06f80aa7029c9e46c16784194d0375d0bfa3170dbb058a188623d5';
