#!/usr/bin/env node
// Mirrors a monorepo app's source into its standalone external repository's
// `master` branch as a single linear-append commit (history preserved, all tracked
// files replaced). The mirrored tree is installable with plain `npm install`:
// every `workspace:`/`catalog:` specifier is resolved (see resolve-manifest.mjs)
// and `node_modules` / build output are NOT committed.
//
// For Architect, the Interviewer preview bundle (built in the monorepo) is vendored
// into the mirror and the electron-builder `extraResources` paths are rewritten to
// point at it, so the standalone repo is self-consistent.
//
// Usage:
//   node scripts/mirror-app.mjs --app <appDir> --repo <owner/name> --version <version> [--with-lockfile]
// Env:
//   LEGACY_RELEASE_GH_TOKEN  cross-repo token with contents:write (required to push)
//   MONOREPO_SHA             source commit sha (recorded in the commit message)
//   GITHUB_OUTPUT            when set, `mirror_sha=<sha>` is appended for the workflow
//   MIRROR_DRY_RUN           when "true", stage + commit locally but skip the push
import { spawnSync } from 'node:child_process';
import {
  appendFileSync,
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve, sep } from 'node:path';

import { resolveManifest } from './resolve-manifest.mjs';

const GITIGNORE = `node_modules/
dist/
out/
release-builds/
.turbo/
coverage/
*.log
.DS_Store
`;

// Strip any embedded credentials (e.g. the tokenized clone URL
// https://x-access-token:<token>@github.com/...) before putting a string into a
// thrown error, so LEGACY_RELEASE_GH_TOKEN never reaches the logs.
function redact(text) {
  return String(text ?? '').replace(/\/\/[^/@\s]+@/g, '//***@');
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', ...opts });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `${cmd} ${redact(args.join(' '))} exited with ${result.status}`,
    );
  }
  return result;
}

function capture(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { encoding: 'utf8', ...opts });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `${cmd} ${redact(args.join(' '))} exited with ${result.status}\n${redact(result.stderr)}`,
    );
  }
  return result.stdout.trim();
}

function parseArgs(argv) {
  const args = { withLockfile: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--with-lockfile') args.withLockfile = true;
    else if (a.startsWith('--')) {
      args[a.slice(2)] = argv[i + 1];
      i += 1;
    }
  }
  return args;
}

// Recursively copy src -> dest, skipping the named top-level entries. Anchored to
// the top level so a legitimately-named nested directory isn't dropped.
function copyTree(src, dest, excludeTopLevel) {
  const exclude = new Set(excludeTopLevel);
  cpSync(src, dest, {
    recursive: true,
    filter: (from) => {
      const rel = relative(src, from);
      if (rel === '') return true;
      return !exclude.has(rel.split(sep)[0]);
    },
  });
}

// Copy the app source into staging, excluding everything regenerated by a build
// or install.
function stageSource(appDir, staging) {
  copyTree(appDir, staging, [
    'node_modules',
    'dist',
    'out',
    'release-builds',
    '.turbo',
    'coverage',
    '.git',
  ]);
}

// Architect renders the Interviewer app in its preview window from a bundle that
// electron-builder copies via extraResources. In the monorepo that bundle lives at
// ../interviewer/out; vendor it into the mirror and repoint the config.
function vendorInterviewerPreview(appDir, staging) {
  const interviewerOut = join(appDir, '..', 'interviewer', 'out');
  const vendorDir = join(staging, 'interviewer-preview');
  for (const part of ['renderer', 'preload']) {
    const from = join(interviewerOut, part);
    if (!existsSync(from)) {
      throw new Error(
        `Cannot vendor Interviewer preview: ${from} not found. Build the interviewer app first.`,
      );
    }
    cpSync(from, join(vendorDir, part), { recursive: true });
  }
  const configPath = join(staging, 'electron-builder.config.js');
  const original = readFileSync(configPath, 'utf8');
  const rendererPattern = /['"]\.\.\/interviewer\/out\/renderer['"]/g;
  const preloadPattern = /['"]\.\.\/interviewer\/out\/preload['"]/g;
  // Fail loudly rather than silently leaving broken extraResources paths in the
  // mirror if the source config's path text ever drifts.
  if (!rendererPattern.test(original) || !preloadPattern.test(original)) {
    throw new Error(
      `Expected ../interviewer/out renderer+preload paths in ${configPath}; ` +
        'the Architect preview vendoring rewrite would be a no-op.',
    );
  }
  const config = original
    .replace(rendererPattern, "'interviewer-preview/renderer'")
    .replace(preloadPattern, "'interviewer-preview/preload'");
  writeFileSync(configPath, config);
}

function main() {
  const { app, repo, version, withLockfile } = parseArgs(process.argv.slice(2));
  if (!app || !repo || !version) {
    console.error(
      'Usage: node scripts/mirror-app.mjs --app <appDir> --repo <owner/name> --version <version> [--with-lockfile]',
    );
    process.exit(1);
  }

  const appDir = resolve(app);
  const manifest = JSON.parse(
    readFileSync(join(appDir, 'package.json'), 'utf8'),
  );
  const appName = manifest.name;
  const dryRun = process.env.MIRROR_DRY_RUN === 'true';
  const token = process.env.LEGACY_RELEASE_GH_TOKEN;
  // MIRROR_REPO_URL overrides the GitHub URL (used by tests against a local
  // remote, and for non-github mirrors). When unset, a token is required to push.
  const repoUrlOverride = process.env.MIRROR_REPO_URL;
  if (!token && !dryRun && !repoUrlOverride) {
    throw new Error('LEGACY_RELEASE_GH_TOKEN is required to push the mirror.');
  }

  const staging = mkdtempSync(join(tmpdir(), 'mirror-stage-'));
  console.error(`[mirror] staging ${appName} -> ${staging}`);

  stageSource(appDir, staging);

  const { manifest: resolved, dropped } = resolveManifest(appDir);
  writeFileSync(
    join(staging, 'package.json'),
    `${JSON.stringify(resolved, null, 2)}\n`,
  );
  if (dropped.length) {
    console.error(
      `[mirror] dropped private workspace deps: ${dropped.join(', ')}`,
    );
  }

  writeFileSync(join(staging, '.gitignore'), GITIGNORE);

  if (appName === 'network-canvas-architect') {
    vendorInterviewerPreview(appDir, staging);
  }

  if (withLockfile) {
    console.error(
      '[mirror] generating package-lock.json (validates npm resolvability)',
    );
    run('npm', ['install', '--package-lock-only', '--ignore-scripts'], {
      cwd: staging,
    });
  }

  // Clone the external master and replace its entire tracked tree with the staging
  // tree, then commit on top (linear append) and push.
  const checkout = mkdtempSync(join(tmpdir(), 'mirror-repo-'));
  const cloneUrl =
    repoUrlOverride ??
    (dryRun
      ? `https://github.com/${repo}.git`
      : `https://x-access-token:${token}@github.com/${repo}.git`);
  run('git', [
    'clone',
    '--branch',
    'master',
    '--single-branch',
    cloneUrl,
    checkout,
  ]);

  run('git', ['-C', checkout, 'rm', '-r', '--quiet', '.']);
  copyTree(staging, checkout, ['.git']);
  run('git', ['-C', checkout, 'add', '-A']);

  // If the mirrored tree is byte-identical to current master (e.g. a forced
  // re-release with no source change), there's nothing to commit — `git commit`
  // would exit non-zero and abort the rerun. Skip commit/push and reuse HEAD.
  const hasChanges =
    spawnSync('git', ['-C', checkout, 'diff', '--cached', '--quiet']).status !==
    0;

  if (hasChanges) {
    const sourceSha =
      process.env.MONOREPO_SHA || capture('git', ['rev-parse', 'HEAD']);
    const message = `Release v${version} (mirrored from monorepo ${sourceSha})`;
    const authorName =
      process.env.GIT_AUTHOR_NAME || 'Network Canvas Release Bot';
    const authorEmail =
      process.env.GIT_AUTHOR_EMAIL || 'releases@networkcanvas.com';
    run('git', [
      '-C',
      checkout,
      '-c',
      `user.name=${authorName}`,
      '-c',
      `user.email=${authorEmail}`,
      '-c',
      'commit.gpgsign=false',
      'commit',
      '-m',
      message,
    ]);

    if (dryRun) {
      console.error('[mirror] MIRROR_DRY_RUN=true — skipping push.');
    } else {
      run('git', ['-C', checkout, 'push', 'origin', 'master']);
    }
  } else {
    console.error(
      '[mirror] no content changes vs current master; reusing existing HEAD.',
    );
  }

  const mirrorSha = capture('git', ['-C', checkout, 'rev-parse', 'HEAD']);
  console.error(`[mirror] ${appName} mirrored at ${mirrorSha}`);
  if (process.env.GITHUB_OUTPUT) {
    appendFileSync(process.env.GITHUB_OUTPUT, `mirror_sha=${mirrorSha}\n`);
  }
}

main();
