# Shared by build.sh's siblings: where the stack's files are, which variants
# exist, and how one Compose project is invoked (#1909).
#
# Sourced, never executed. Every caller sets `set -euo pipefail` itself, so a
# failure inside a function here stops the script that called it.
#
# The invocation is in one place for the reason server/scripts/compose.ts gives
# for the same thing: a second copy of the `-p`, the `-f` chain and the
# `--env-file` is how two scripts drift into disagreeing about which files are
# applied and which project a `down` tears apart.

STACK_TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STUDIO_DIR="$(cd "$STACK_TEST_DIR/.." && pwd)"
# Everything generated by a run: the environment file, the token `migrate`
# printed, own-proxy's nginx configuration and certificate, and the `ps` and
# logs `down.sh` saves on its way out. Gitignored, and cleared by the next
# `up.sh` rather than by `down.sh` — a variant that failed has to stay
# explainable after it has been torn down.
WORK_DIR="$STACK_TEST_DIR/.work"
ENV_FILE="$WORK_DIR/.env.ci"
TOKEN_FILE="$WORK_DIR/setup-token"
PROJECT="studio-ci"

# `reference` first: it is the stack a self-hoster runs, and each of the others
# is that stack with one element replaced.
VARIANTS=(reference external-postgres external-bucket external-redis own-proxy)

# The stack's own network. Also TRUSTED_PROXIES, so it must name the network
# the ingress is on and nothing else. .243 rather than .240 (`.env.example`),
# .241 (`pnpm dev`) or .242 (`dev:stack`), so this lane can run beside all
# three.
STACK_SUBNET="172.31.243.0/24"
# The stubs' network: a different network, so a swap is a real one — the stack
# reaches the institution's service across a boundary rather than over its own
# bridge.
EXTERNAL_NETWORK="studio-ci-external"
EXTERNAL_SUBNET="172.31.244.0/24"

HOSTNAME_="localhost"
API_IMAGE="${API_IMAGE:-studio-api:ci}"
WEB_IMAGE="${WEB_IMAGE:-studio-web:ci}"

# own-proxy publishes nginx here instead, because it is a different ingress on
# a host where the reference lane's 443 may be in use by a stack somebody
# forgot to stop.
OWN_PROXY_PORT=8443

say() { echo "[stack-test] $*"; }

die() {
  echo "[stack-test] $*" >&2
  exit 1
}

# Sets VARIANT from `--variant <name>`, rejecting anything not in VARIANTS.
parse_variant() {
  VARIANT=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --variant)
        [ $# -ge 2 ] || die "--variant needs a value"
        VARIANT="$2"
        shift 2
        ;;
      *) die "Unknown argument: $1" ;;
    esac
  done
  [ -n "$VARIANT" ] || die "--variant is required (one of: ${VARIANTS[*]})"
  local known
  for known in "${VARIANTS[@]}"; do
    [ "$known" = "$VARIANT" ] && return 0
  done
  die "Unknown variant '$VARIANT' (one of: ${VARIANTS[*]})"
}

variant_file() {
  local path="$STACK_TEST_DIR/variants/$1.yml"
  [ -f "$path" ] || die "No override for variant '$1' at $path"
  echo "$path"
}

# One Compose project: the project name, the three files and the environment
# file, fixed here so no caller can name three of the four.
#
# `docker-compose.local.yml` is applied to every variant and is not optional:
# it is what points Traefik at a certificate authority that does not answer, so
# the stack serves its own self-signed certificate rather than asking Let's
# Encrypt for `localhost`. Restating its Traefik command list here would be a
# second copy of the production flag list to keep in step.
compose() {
  docker compose \
    -p "$PROJECT" \
    --env-file "$ENV_FILE" \
    -f "$STUDIO_DIR/docker-compose.yml" \
    -f "$STUDIO_DIR/docker-compose.local.yml" \
    -f "$(variant_file "$VARIANT")" \
    "$@"
}

# Where the ingress answers for this variant. Traefik for three of them; for
# own-proxy the nginx block the guide documents, on a loopback port of its own.
ingress_url() {
  if [ "$VARIANT" = "own-proxy" ]; then
    echo "https://$HOSTNAME_:$OWN_PROXY_PORT"
  else
    echo "https://$HOSTNAME_"
  fi
}

# The Origin every browser request carries, and the one the server's same-origin
# gate compares against: PUBLIC_URL, which is the hostname without a port
# whichever ingress is in front. own-proxy is reached on 8443 and still presents
# this Origin, exactly as a deployment on 443 would.
origin_url() { echo "https://$HOSTNAME_"; }

# Which Compose service holds the rate limiter's counters for this variant.
# The stack's own Valkey everywhere except the swap that replaces it, where
# the stub is the whole point: `assert.sh` reads the limiter's keys out of
# whichever this names, so the swap is proved by the counters being in the
# store `REDIS_URL` points at rather than by the stack merely still working.
limiter_store_service() {
  if [ "$VARIANT" = "external-redis" ]; then
    echo 'external-valkey'
  else
    echo 'valkey'
  fi
}
