import { writeFile } from 'node:fs/promises';

import { renderRegistrySchema } from './schema.ts';

const { fingerprint } = await renderRegistrySchema();
await writeFile(
  new URL('../src/db/fingerprint.generated.ts', import.meta.url),
  [
    '// Generated by scripts/sync-fingerprint.ts. Do not edit.',
    `export const REGISTRY_SCHEMA_FINGERPRINT = '${fingerprint}';`,
    '',
  ].join('\n'),
);
