import type { BackgroundDocument, Zone } from '../model/types';

function formatNumber(value: number): string {
  return String(value);
}

// Escape an arbitrary label into a Python double-quoted string literal. Built
// deliberately (rather than trusting JSON.stringify, whose output is only
// coincidentally valid Python) so backslashes, quotes, newlines and other
// control characters cannot break out of the literal or the surrounding source.
// Python string literals accept a literal nul, but for parity with the R
// emitter (where "\x00" is a hard error) U+0000 is replaced with U+FFFD in both.
function pyString(value: string): string {
  let out = '"';
  for (const ch of value) {
    const code = ch.codePointAt(0) ?? 0;
    switch (ch) {
      case '\\':
        out += '\\\\';
        break;
      case '"':
        out += '\\"';
        break;
      case '\n':
        out += '\\n';
        break;
      case '\r':
        out += '\\r';
        break;
      case '\t':
        out += '\\t';
        break;
      default:
        if (code === 0) {
          out += '�';
        } else if (code < 0x20) {
          out += `\\x${code.toString(16).padStart(2, '0')}`;
        } else {
          out += ch;
        }
    }
  }
  return `${out}"`;
}

function pyZoneLiteral(zone: Zone): string {
  const label = pyString(zone.label);
  if (zone.shape === 'rect') {
    return `    {"label": ${label}, "shape": "rect", "x": ${formatNumber(zone.x)}, "y": ${formatNumber(zone.y)}, "width": ${formatNumber(zone.width)}, "height": ${formatNumber(zone.height)}},`;
  }
  if (zone.shape === 'circle') {
    return `    {"label": ${label}, "shape": "circle", "cx": ${formatNumber(zone.cx)}, "cy": ${formatNumber(zone.cy)}, "r": ${formatNumber(zone.r)}},`;
  }
  const points = zone.points
    .map((p) => `[${formatNumber(p.x)}, ${formatNumber(p.y)}]`)
    .join(', ');
  return `    {"label": ${label}, "shape": "polygon", "points": [${points}]},`;
}

function commentLine(value: string): string {
  return value.replace(/\r?\n/g, ' ');
}

export function generatePythonScript(
  doc: BackgroundDocument,
  opts: { layoutVariable: string; outputVariable: string },
): string {
  const zones = doc.zones.map(pyZoneLiteral).join('\n');
  const title = commentLine(doc.title);
  const layoutDefault = pyString(opts.layoutVariable);
  const outputDefault = pyString(opts.outputVariable);

  return `#!/usr/bin/env python3
# Generated by Network Canvas Background Creator.
# Background: ${title}
#
# Assigns a categorical zone label to each node from its layout-variable
# position and writes the result to a new column.
#
# Coordinates are normalized to the range 0-1 with the origin at the top-left
# corner and y increasing downward - the same values Network Canvas stores for
# a layout variable.
#
# This script reads a Network Canvas CSV attribute-list export. It expects the
# columns "<layout>_x" and "<layout>_y" (lowercase, as written by the CSV
# exporter). GraphML exports name the same values "<layout>_X" / "<layout>_Y"
# (uppercase); rename those columns before running this script on GraphML data.
#
# Usage:
#   python assign_zones.py input.csv output.csv
#   python assign_zones.py input.csv output.csv \\
#       --layout-variable location --output-variable zone
#
# Python 3 standard library only - no third-party dependencies.

import argparse
import csv
import math
import sys

ZONES = [
${zones}
]


def point_in_polygon(x, y, points):
    if len(points) < 3:
        return False
    inside = False
    j = len(points) - 1
    for i in range(len(points)):
        xi, yi = points[i]
        xj, yj = points[j]
        if ((yi > y) != (yj > y)) and (
            x < (xj - xi) * (y - yi) / (yj - yi) + xi
        ):
            inside = not inside
        j = i
    return inside


def point_in_zone(x, y, zone):
    shape = zone["shape"]
    if shape == "rect":
        return (
            zone["x"] <= x <= zone["x"] + zone["width"]
            and zone["y"] <= y <= zone["y"] + zone["height"]
        )
    if shape == "circle":
        # A zero- or negative-radius circle contains nothing; guard before
        # dividing so this never raises ZeroDivisionError.
        if zone["r"] <= 0:
            return False
        dx = (x - zone["cx"]) / zone["r"]
        dy = (y - zone["cy"]) / zone["r"]
        return dx * dx + dy * dy <= 1
    if shape == "polygon":
        return point_in_polygon(x, y, zone["points"])
    return False


def zone_area(zone):
    shape = zone["shape"]
    if shape == "rect":
        return zone["width"] * zone["height"]
    if shape == "circle":
        return math.pi * zone["r"] * zone["r"]
    if shape == "polygon":
        points = zone["points"]
        total = 0.0
        j = len(points) - 1
        for i in range(len(points)):
            xi, yi = points[i]
            xj, yj = points[j]
            total += xj * yi - xi * yj
            j = i
        return abs(total) / 2
    return 0.0


def assign_zone(x, y):
    best_label = None
    best_area = None
    for zone in ZONES:
        if not point_in_zone(x, y, zone):
            continue
        area = zone_area(zone)
        # Smallest containing zone wins; on an exact area tie the later zone in
        # document order wins, so "<=" lets a later equal-area zone replace an
        # earlier one.
        if best_area is None or area <= best_area:
            best_area = area
            best_label = zone["label"]
    return best_label


def parse_coordinate(value):
    if value is None:
        return None
    text = value.strip()
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


def main(argv):
    parser = argparse.ArgumentParser(
        description="Assign a Network Canvas background zone to each node.",
    )
    parser.add_argument("input", help="Input CSV (Network Canvas node export).")
    parser.add_argument("output", help="Output CSV file to write.")
    parser.add_argument(
        "--layout-variable",
        default=${layoutDefault},
        help="Name of the layout variable (default: %(default)s).",
    )
    parser.add_argument(
        "--output-variable",
        default=${outputDefault},
        help="Name of the column to add (default: %(default)s).",
    )
    args = parser.parse_args(argv)

    x_column = f"{args.layout_variable}_x"
    y_column = f"{args.layout_variable}_y"

    # utf-8-sig transparently strips a leading UTF-8 BOM if present, so the
    # first column name is not silently prefixed with U+FEFF.
    with open(args.input, newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        fieldnames = list(reader.fieldnames or [])
        missing = [name for name in (x_column, y_column) if name not in fieldnames]
        if missing:
            found = ", ".join(fieldnames) if fieldnames else "(none)"
            print(
                f"Error: input is missing required column(s): {', '.join(missing)}.",
                file=sys.stderr,
            )
            print(f"Found columns: {found}.", file=sys.stderr)
            return 1
        if args.output_variable in fieldnames:
            print(
                f'Error: output column "{args.output_variable}" already exists '
                "in the input.",
                file=sys.stderr,
            )
            return 1
        rows = list(reader)

    output_fieldnames = fieldnames + [args.output_variable]
    with open(args.output, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=output_fieldnames)
        writer.writeheader()
        for index, row in enumerate(rows, start=1):
            # DictReader collects any cells beyond the header under the None
            # restkey; fail cleanly rather than letting DictWriter raise a raw
            # ValueError on the unexpected field.
            if None in row:
                print(
                    f"Error: row {index} has more cells than the header "
                    f"({len(fieldnames)} columns).",
                    file=sys.stderr,
                )
                return 1
            x = parse_coordinate(row.get(x_column))
            y = parse_coordinate(row.get(y_column))
            label = assign_zone(x, y) if x is not None and y is not None else None
            row[args.output_variable] = "" if label is None else label
            writer.writerow(row)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
`;
}
