import type { BackgroundDocument, Zone } from '../model/types';

function formatNumber(value: number): string {
  return String(value);
}

// Escape an arbitrary label into an R double-quoted string literal. Built
// deliberately so backslashes, quotes, newlines and control characters cannot
// break out of the literal; R accepts the same \\ \" \n \r \t and \xNN escapes
// used here.
function rString(value: string): string {
  let out = '"';
  for (const ch of value) {
    const code = ch.codePointAt(0) ?? 0;
    switch (ch) {
      case '\\':
        out += '\\\\';
        break;
      case '"':
        out += '\\"';
        break;
      case '\n':
        out += '\\n';
        break;
      case '\r':
        out += '\\r';
        break;
      case '\t':
        out += '\\t';
        break;
      default:
        out += code < 0x20 ? `\\x${code.toString(16).padStart(2, '0')}` : ch;
    }
  }
  return `${out}"`;
}

function rZoneLiteral(zone: Zone): string {
  const label = rString(zone.label);
  if (zone.shape === 'rect') {
    return `  list(label = ${label}, shape = "rect", x = ${formatNumber(zone.x)}, y = ${formatNumber(zone.y)}, width = ${formatNumber(zone.width)}, height = ${formatNumber(zone.height)})`;
  }
  if (zone.shape === 'circle') {
    return `  list(label = ${label}, shape = "circle", cx = ${formatNumber(zone.cx)}, cy = ${formatNumber(zone.cy)}, r = ${formatNumber(zone.r)})`;
  }
  const points = zone.points
    .map((p) => `c(${formatNumber(p.x)}, ${formatNumber(p.y)})`)
    .join(', ');
  return `  list(label = ${label}, shape = "polygon", points = list(${points}))`;
}

function commentLine(value: string): string {
  return value.replace(/\r?\n/g, ' ');
}

export function generateRScript(
  doc: BackgroundDocument,
  opts: { layoutVariable: string; outputVariable: string },
): string {
  const zones = doc.zones.map(rZoneLiteral).join(',\n');
  const title = commentLine(doc.title);
  const layoutDefault = rString(opts.layoutVariable);
  const outputDefault = rString(opts.outputVariable);

  return `#!/usr/bin/env Rscript
# Generated by Network Canvas Background Creator.
# Background: ${title}
#
# Assigns a categorical zone label to each node from its layout-variable
# position and writes the result to a new column.
#
# Coordinates are normalized to the range 0-1 with the origin at the top-left
# corner and y increasing downward - the same values Network Canvas stores for
# a layout variable.
#
# This script reads a Network Canvas CSV attribute-list export. It expects the
# columns "<layout>_x" and "<layout>_y" (lowercase, as written by the CSV
# exporter). GraphML exports name the same values "<layout>_X" / "<layout>_Y"
# (uppercase); rename those columns before running this script on GraphML data.
#
# Usage:
#   Rscript assign_zones.R input.csv output.csv
#   Rscript assign_zones.R input.csv output.csv \\
#       --layout-variable=location --output-variable=zone
#
# Base R only - no packages required.

zones <- list(
${zones}
)

point_in_polygon <- function(x, y, points) {
  n <- length(points)
  if (n < 3) {
    return(FALSE)
  }
  inside <- FALSE
  j <- n
  for (i in seq_len(n)) {
    xi <- points[[i]][1]
    yi <- points[[i]][2]
    xj <- points[[j]][1]
    yj <- points[[j]][2]
    if (((yi > y) != (yj > y)) &&
      (x < (xj - xi) * (y - yi) / (yj - yi) + xi)) {
      inside <- !inside
    }
    j <- i
  }
  inside
}

point_in_zone <- function(x, y, zone) {
  if (zone$shape == "rect") {
    return(x >= zone$x && x <= zone$x + zone$width &&
      y >= zone$y && y <= zone$y + zone$height)
  }
  if (zone$shape == "circle") {
    dx <- (x - zone$cx) / zone$r
    dy <- (y - zone$cy) / zone$r
    return(dx * dx + dy * dy <= 1)
  }
  if (zone$shape == "polygon") {
    return(point_in_polygon(x, y, zone$points))
  }
  FALSE
}

zone_area <- function(zone) {
  if (zone$shape == "rect") {
    return(zone$width * zone$height)
  }
  if (zone$shape == "circle") {
    return(pi * zone$r * zone$r)
  }
  if (zone$shape == "polygon") {
    points <- zone$points
    n <- length(points)
    total <- 0
    j <- n
    for (i in seq_len(n)) {
      xi <- points[[i]][1]
      yi <- points[[i]][2]
      xj <- points[[j]][1]
      yj <- points[[j]][2]
      total <- total + (xj * yi - xi * yj)
      j <- i
    }
    return(abs(total) / 2)
  }
  0
}

# Smallest containing zone wins; on an exact area tie the later zone in document
# order wins, so "<=" lets a later equal-area zone replace an earlier one.
assign_zone <- function(x, y) {
  if (is.na(x) || is.na(y)) {
    return(NA_character_)
  }
  best_label <- NA_character_
  best_area <- NA_real_
  for (zone in zones) {
    if (!point_in_zone(x, y, zone)) {
      next
    }
    area <- zone_area(zone)
    if (is.na(best_area) || area <= best_area) {
      best_area <- area
      best_label <- zone$label
    }
  }
  best_label
}

parse_coordinate <- function(value) {
  if (length(value) == 0 || is.na(value)) {
    return(NA_real_)
  }
  text <- trimws(as.character(value))
  if (text == "") {
    return(NA_real_)
  }
  suppressWarnings(as.numeric(text))
}

args <- commandArgs(trailingOnly = TRUE)
layout_variable <- ${layoutDefault}
output_variable <- ${outputDefault}
positional <- character(0)
for (arg in args) {
  if (startsWith(arg, "--layout-variable=")) {
    layout_variable <- substring(arg, nchar("--layout-variable=") + 1)
  } else if (startsWith(arg, "--output-variable=")) {
    output_variable <- substring(arg, nchar("--output-variable=") + 1)
  } else {
    positional <- c(positional, arg)
  }
}

if (length(positional) < 2) {
  cat(
    "Usage: Rscript assign_zones.R input.csv output.csv",
    "[--layout-variable=NAME] [--output-variable=NAME]\\n",
    file = stderr()
  )
  quit(status = 1)
}

input_path <- positional[1]
output_path <- positional[2]
x_column <- paste0(layout_variable, "_x")
y_column <- paste0(layout_variable, "_y")

data <- read.csv(input_path, stringsAsFactors = FALSE, check.names = FALSE)
columns <- names(data)
missing <- setdiff(c(x_column, y_column), columns)
if (length(missing) > 0) {
  found <- if (length(columns) > 0) paste(columns, collapse = ", ") else "(none)"
  cat(
    sprintf(
      "Error: input is missing required column(s): %s.\\n",
      paste(missing, collapse = ", ")
    ),
    file = stderr()
  )
  cat(sprintf("Found columns: %s.\\n", found), file = stderr())
  quit(status = 1)
}
if (output_variable %in% columns) {
  cat(
    sprintf(
      "Error: output column \\"%s\\" already exists in the input.\\n",
      output_variable
    ),
    file = stderr()
  )
  quit(status = 1)
}

xs <- vapply(data[[x_column]], parse_coordinate, numeric(1))
ys <- vapply(data[[y_column]], parse_coordinate, numeric(1))
labels <- vapply(
  seq_len(nrow(data)),
  function(i) assign_zone(xs[i], ys[i]),
  character(1)
)
data[[output_variable]] <- labels
write.csv(data, output_path, row.names = FALSE, na = "")
`;
}
