- main:
  - toolbar "Network composer tools":
    - button "Select" [pressed]
    - button "Add node"
    - button "Groups"
    - separator
    - button "Automatic layout"
    - separator
    - button "Undo"
    - button "Redo" [disabled]
  - region "Group membership options":
    - group "Group membership for selected people":
      - button "School"
      - button "Work" [pressed]
      - button "Family"
      - button "My partner's family"
      - button "Friends"
      - button "Neighborhood"
      - button "Community or faith group"
      - button "Services and professionals"
      - button "Online"
  - application:
    - img
    - button "Ida"
    - button "Jack"
    - button "Kim"
  - navigation:
    - button "Previous Step" [disabled]
    - progressbar "Progress indicator": x
    - button "Next Step"
  - region "Interview notifications"