- main:
  - toolbar "Network composer tools":
    - group "Editing tools":
      - button "Select" [pressed]
      - button "Add node"
      - button "Draw edge"
      - button "Groups"
    - separator
    - group "Layout tools":
      - button "Automatic layout"
    - separator
    - group "History tools":
      - button "Undo" [disabled]
      - button "Redo"
  - application:
    - img
    - button "Quinn"
    - button "Rita"
  - navigation:
    - button "Previous Step" [disabled]
    - progressbar "Progress indicator": x
    - button "Next Step"
  - region "Interview notifications"