- main:
  - toolbar "Network composer tools":
    - button "Select" [pressed]
    - button "Add node"
    - button "Draw edge"
    - separator
    - button "Automatic layout" [pressed]
    - separator
    - button "Undo" [disabled]
    - button "Redo" [disabled]
  - application:
    - img
    - button "Toni Collier"
    - button "Vernie Jerde"
    - button "Odell Schmitt"
    - button "Tami Stoltenberg"
  - navigation:
    - button "Previous Step" [disabled]
    - progressbar "Progress indicator": x
    - button "Next Step"
  - region "Interview notifications"