name: Link Checker

on: deployment_status

jobs:
  linkinator:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.deployment_status.environment_url, 'https://documentation') && github.event.deployment_status.state == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup npm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Linkinator
        run: pnpm linkinator ${{ github.event.deployment_status.environment_url}} -r
