name: Link Checker

on: deployment_status

defaults:
  run:
    working-directory: apps/documentation

jobs:
  linkinator:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.deployment_status.repository_url, 'documentation') && github.event.deployment_status.state == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Linkinator
        run: pnpm linkinator ${{ github.event.deployment_status.environment_url}} -r
