name: Link Checker

on: deployment_status

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          recurse: true
          paths: ${{ github.event.deployment_status.environment_url }}
