name: Check for Broken Links

on:
  deployment_status
jobs:
  linkinator:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.deployment_status.environment, 'preview') && github.event.deployment_status.state == 'success' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Linkinator
        run: npm install -g linkinator
      - name: Run Linkinator against the preview URL
        run: linkinator ${{ github.event.deployment_status.environment_url }} -r
