name: CI and Release (Optimized)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read      # Allow reading repository contents
  packages: read      # Allow reading GitHub Packages
  actions: read       # Allow read-only access to workflow runs and jobs
  checks: write       # Allow updating check runs (needed for changesets/action)
  pull-requests: write # Allow creating pull requests (needed for changesets/action)

jobs:
  # Setup job that all other jobs depend on
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache-hit: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      # Cache node_modules based on pnpm-lock.yaml
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      # Cache pnpm store for faster installs
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      # Only install if cache miss
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
      
      - name: Build shared-consts
        run: pnpm --filter @codaco/shared-consts build
      
      # Upload shared-consts build as artifact
      - name: Upload shared-consts build
        uses: actions/upload-artifact@v4
        with:
          name: shared-consts-dist
          path: packages/shared-consts/dist
          retention-days: 1

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      # Restore cached node_modules
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      - name: Download shared-consts build
        uses: actions/download-artifact@v4
        with:
          name: shared-consts-dist
          path: packages/shared-consts/dist
      
      - name: Check formatting
        run: pnpm lint
      
      - name: Typecheck
        run: pnpm typecheck

      - name: Knip
        run: pnpm knip

  test:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env: 
      PROTOCOL_ENCRYPTION_KEY: ${{ secrets.PROTOCOL_ENCRYPTION_KEY }}
      PROTOCOL_ENCRYPTION_IV: ${{ secrets.PROTOCOL_ENCRYPTION_IV }}
      GITHUB_TOKEN: ${{ secrets.TEST_PROTOCOL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      # Restore cached node_modules
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      - name: Download shared-consts build
        uses: actions/download-artifact@v4
        with:
          name: shared-consts-dist
          path: packages/shared-consts/dist
      
      - name: Create .env file and run tests
        run: |
          echo "PROTOCOL_ENCRYPTION_KEY=${{ secrets.PROTOCOL_ENCRYPTION_KEY }}" > packages/protocol-validation/.env
          echo "PROTOCOL_ENCRYPTION_IV=${{ secrets.PROTOCOL_ENCRYPTION_IV }}" >> packages/protocol-validation/.env
          echo "GITHUB_TOKEN=${{ secrets.TEST_PROTOCOL_TOKEN }}" >> packages/protocol-validation/.env
          pnpm test

  release:
    permissions:
      contents: write
      pull-requests: write
    # Only run on main branch pushes (not PRs) and only if lint and test jobs succeed
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [setup, lint, test]
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DOCS_PATH: "docs"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    
    # Restore cached node_modules
    - name: Restore node_modules cache
      uses: actions/cache/restore@v4
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    
    - name: Download shared-consts build
      uses: actions/download-artifact@v4
      with:
        name: shared-consts-dist
        path: packages/shared-consts/dist
    
    # Build only packages with changesets
    - name: Build changed packages only
      run: pnpm run build:changed-packages
    
    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
        # command used to version packages. Lint and fix to avoid errors caused 
        # by versioning
        version: pnpm run version-packages
        # Runs changesets publish. versioning is done by changesets action
        publish: pnpm run publish-packages
        createGithubReleases: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
