name: Development Protocol CI
on:
  pull_request:
    paths:
      - 'packages/development-protocol'
      - 'packages/protocol-validation'
  push:
    paths:
      - 'packages/development-protocol'
      - 'packages/protocol-validation'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Set node version (using the latest LTS version)
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      # Setup pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: ZIP development protocol
        run: zip Development.netcanvas * -r -0

      - name: Checkout protocol validation
        uses: actions/checkout@v4
        with:
          repository: complexdatacollective/protocol-validation
          ref: feature/schema-version-8
          path: protocol-validation

      - name: Install protocol validation with pnpm
        run: |
          cd protocol-validation
          pnpm install

      - name: Validate protocol
        run: |
          cd protocol-validation
          pnpm run validate-protocol ../Development.netcanvas