name: Development Protocol Validate
on:
  pull_request:
    paths:
      - 'packages/development-protocol'
      - 'packages/protocol-validation'
  push:
    paths:
      - 'packages/development-protocol'
      - 'packages/protocol-validation'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    defaults:
      run:
        working-directory: ./packages/protocol-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      # Setup pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Build protocol-validation
      - name: Build protocol validation
        run: |
          pnpm install
          pnpm build

      - name: Validate protocol
        run: node ./scipts/cli.js ../development-protocol/protocol.json
